# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Locationspec"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Locationspec(BaseModel):
  """Holds the entity location information."""


class LocationspecResponse(APIResponse):
  """Response model for Locationspec"""

  data: Optional[Locationspec] = None


class LocationspecListResponse(APIResponse):
  """List response model for Locationspec"""

  data: List[Locationspec] = Field(default_factory=list)
  pagination: Optional[PaginationInfo] = None
