# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Recursivepartialentityrelation"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Recursivepartialentityrelation(BaseModel):
  """A relation of a specific type to another entity in the catalog."""


class RecursivepartialentityrelationResponse(APIResponse):
  """Response model for Recursivepartialentityrelation"""

  data: Optional[Recursivepartialentityrelation] = None


class RecursivepartialentityrelationListResponse(APIResponse):
  """List response model for Recursivepartialentityrelation"""

  data: List[Recursivepartialentityrelation] = Field(default_factory=list)
  pagination: Optional[PaginationInfo] = None
