# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /api/v1/applicationsets/generate operations"""

import logging
from typing import Dict, Any, List
from agent_argocd.protocol_bindings.mcp_server.mcp_argocd.api.client import make_api_request


def assemble_nested_body(flat_body: Dict[str, Any]) -> Dict[str, Any]:
    '''
    Convert a flat dictionary with underscore-separated keys into a nested dictionary.

    Args:
        flat_body (Dict[str, Any]): A dictionary where keys are underscore-separated strings representing nested paths.

    Returns:
        Dict[str, Any]: A nested dictionary constructed from the flat dictionary.

    Raises:
        ValueError: If the input dictionary contains keys that cannot be split into valid parts.
    '''
    nested = {}
    for key, value in flat_body.items():
        parts = key.split("_")
        d = nested
        for part in parts[:-1]:
            d = d.setdefault(part, {})
        d[parts[-1]] = value
    return nested


# Configure logging
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger("mcp_tools")


async def application_set_service__generate(
    body_applicationSet_metadata_annotations: Dict[str, Any] = None,
    body_applicationSet_metadata_creationTimestamp: str = None,
    body_applicationSet_metadata_deletionGracePeriodSeconds: int = None,
    body_applicationSet_metadata_deletionTimestamp: str = None,
    body_applicationSet_metadata_finalizers: List[str] = None,
    body_applicationSet_metadata_generateName: str = None,
    body_applicationSet_metadata_generation: int = None,
    body_applicationSet_metadata_labels: Dict[str, Any] = None,
    body_applicationSet_metadata_managedFields: List[str] = None,
    body_applicationSet_metadata_name: str = None,
    body_applicationSet_metadata_namespace: str = None,
    body_applicationSet_metadata_ownerReferences: List[str] = None,
    body_applicationSet_metadata_resourceVersion: str = None,
    body_applicationSet_metadata_selfLink: str = None,
    body_applicationSet_metadata_uid: str = None,
    body_applicationSet_spec_applyNestedSelectors: bool = None,
    body_applicationSet_spec_generators: List[str] = None,
    body_applicationSet_spec_goTemplate: bool = None,
    body_applicationSet_spec_goTemplateOptions: List[str] = None,
    body_applicationSet_spec_ignoreApplicationDifferences: List[str] = None,
    body_applicationSet_spec_preservedFields_annotations: List[str] = None,
    body_applicationSet_spec_preservedFields_labels: List[str] = None,
    body_applicationSet_spec_strategy_rollingSync_steps: List[str] = None,
    body_applicationSet_spec_strategy_type: str = None,
    body_applicationSet_spec_syncPolicy_applicationsSync: str = None,
    body_applicationSet_spec_syncPolicy_preserveResourcesOnDeletion: bool = None,
    body_applicationSet_spec_template_metadata_annotations: Dict[str, Any] = None,
    body_applicationSet_spec_template_metadata_finalizers: List[str] = None,
    body_applicationSet_spec_template_metadata_labels: Dict[str, Any] = None,
    body_applicationSet_spec_template_metadata_name: str = None,
    body_applicationSet_spec_template_metadata_namespace: str = None,
    body_applicationSet_spec_template_spec_destination_name: str = None,
    body_applicationSet_spec_template_spec_destination_namespace: str = None,
    body_applicationSet_spec_template_spec_destination_server: str = None,
    body_applicationSet_spec_template_spec_ignoreDifferences: List[str] = None,
    body_applicationSet_spec_template_spec_info: List[str] = None,
    body_applicationSet_spec_template_spec_project: str = None,
    body_applicationSet_spec_template_spec_revisionHistoryLimit: int = None,
    body_applicationSet_spec_template_spec_source_chart: str = None,
    body_applicationSet_spec_template_spec_source_directory_exclude: str = None,
    body_applicationSet_spec_template_spec_source_directory_include: str = None,
    body_applicationSet_spec_template_spec_source_directory_jsonnet_extVars: List[str] = None,
    body_applicationSet_spec_template_spec_source_directory_jsonnet_libs: List[str] = None,
    body_applicationSet_spec_template_spec_source_directory_jsonnet_tlas: List[str] = None,
    body_applicationSet_spec_template_spec_source_directory_recurse: bool = None,
    body_applicationSet_spec_template_spec_source_helm_apiVersions: List[str] = None,
    body_applicationSet_spec_template_spec_source_helm_fileParameters: List[str] = None,
    body_applicationSet_spec_template_spec_source_helm_ignoreMissingValueFiles: bool = None,
    body_applicationSet_spec_template_spec_source_helm_kubeVersion: str = None,
    body_applicationSet_spec_template_spec_source_helm_namespace: str = None,
    body_applicationSet_spec_template_spec_source_helm_parameters: List[str] = None,
    body_applicationSet_spec_template_spec_source_helm_passCredentials: bool = None,
    body_applicationSet_spec_template_spec_source_helm_releaseName: str = None,
    body_applicationSet_spec_template_spec_source_helm_skipCrds: bool = None,
    body_applicationSet_spec_template_spec_source_helm_skipSchemaValidation: bool = None,
    body_applicationSet_spec_template_spec_source_helm_skipTests: bool = None,
    body_applicationSet_spec_template_spec_source_helm_valueFiles: List[str] = None,
    body_applicationSet_spec_template_spec_source_helm_values: str = None,
    body_applicationSet_spec_template_spec_source_helm_valuesObject_raw: str = None,
    body_applicationSet_spec_template_spec_source_helm_version: str = None,
    body_applicationSet_spec_template_spec_source_kustomize_apiVersions: List[str] = None,
    body_applicationSet_spec_template_spec_source_kustomize_commonAnnotations: Dict[str, Any] = None,
    body_applicationSet_spec_template_spec_source_kustomize_commonAnnotationsEnvsubst: bool = None,
    body_applicationSet_spec_template_spec_source_kustomize_commonLabels: Dict[str, Any] = None,
    body_applicationSet_spec_template_spec_source_kustomize_components: List[str] = None,
    body_applicationSet_spec_template_spec_source_kustomize_forceCommonAnnotations: bool = None,
    body_applicationSet_spec_template_spec_source_kustomize_forceCommonLabels: bool = None,
    body_applicationSet_spec_template_spec_source_kustomize_ignoreMissingComponents: bool = None,
    body_applicationSet_spec_template_spec_source_kustomize_images: List[str] = None,
    body_applicationSet_spec_template_spec_source_kustomize_kubeVersion: str = None,
    body_applicationSet_spec_template_spec_source_kustomize_labelIncludeTemplates: bool = None,
    body_applicationSet_spec_template_spec_source_kustomize_labelWithoutSelector: bool = None,
    body_applicationSet_spec_template_spec_source_kustomize_namePrefix: str = None,
    body_applicationSet_spec_template_spec_source_kustomize_nameSuffix: str = None,
    body_applicationSet_spec_template_spec_source_kustomize_namespace: str = None,
    body_applicationSet_spec_template_spec_source_kustomize_patches: List[str] = None,
    body_applicationSet_spec_template_spec_source_kustomize_replicas: List[str] = None,
    body_applicationSet_spec_template_spec_source_kustomize_version: str = None,
    body_applicationSet_spec_template_spec_source_name: str = None,
    body_applicationSet_spec_template_spec_source_path: str = None,
    body_applicationSet_spec_template_spec_source_plugin_env: List[str] = None,
    body_applicationSet_spec_template_spec_source_plugin_name: str = None,
    body_applicationSet_spec_template_spec_source_plugin_parameters: List[str] = None,
    body_applicationSet_spec_template_spec_source_ref: str = None,
    body_applicationSet_spec_template_spec_source_repoURL: str = None,
    body_applicationSet_spec_template_spec_source_targetRevision: str = None,
    body_applicationSet_spec_template_spec_sourceHydrator_drySource_path: str = None,
    body_applicationSet_spec_template_spec_sourceHydrator_drySource_repoURL: str = None,
    body_applicationSet_spec_template_spec_sourceHydrator_drySource_targetRevision: str = None,
    body_applicationSet_spec_template_spec_sourceHydrator_hydrateTo_targetBranch: str = None,
    body_applicationSet_spec_template_spec_sourceHydrator_syncSource_path: str = None,
    body_applicationSet_spec_template_spec_sourceHydrator_syncSource_targetBranch: str = None,
    body_applicationSet_spec_template_spec_sources: List[str] = None,
    body_applicationSet_spec_template_spec_syncPolicy_automated_allowEmpty: bool = None,
    body_applicationSet_spec_template_spec_syncPolicy_automated_enable: bool = None,
    body_applicationSet_spec_template_spec_syncPolicy_automated_prune: bool = None,
    body_applicationSet_spec_template_spec_syncPolicy_automated_selfHeal: bool = None,
    body_applicationSet_spec_template_spec_syncPolicy_managedNamespaceMetadata_annotations: Dict[str, Any] = None,
    body_applicationSet_spec_template_spec_syncPolicy_managedNamespaceMetadata_labels: Dict[str, Any] = None,
    body_applicationSet_spec_template_spec_syncPolicy_retry_backoff_duration: str = None,
    body_applicationSet_spec_template_spec_syncPolicy_retry_backoff_factor: int = None,
    body_applicationSet_spec_template_spec_syncPolicy_retry_backoff_maxDuration: str = None,
    body_applicationSet_spec_template_spec_syncPolicy_retry_limit: int = None,
    body_applicationSet_spec_template_spec_syncPolicy_syncOptions: List[str] = None,
    body_applicationSet_spec_templatePatch: str = None,
    body_applicationSet_status_applicationStatus: List[str] = None,
    body_applicationSet_status_conditions: List[str] = None,
    body_applicationSet_status_resources: List[str] = None,
) -> Dict[str, Any]:
    '''
    Generate an application set service.

    Args:
        body_applicationSet_metadata_annotations (Dict[str, Any], optional): Annotations for the application set metadata.
        body_applicationSet_metadata_creationTimestamp (str, optional): Creation timestamp for the application set metadata.
        body_applicationSet_metadata_deletionGracePeriodSeconds (int, optional): Deletion grace period in seconds for the application set metadata.
        body_applicationSet_metadata_deletionTimestamp (str, optional): Deletion timestamp for the application set metadata.
        body_applicationSet_metadata_finalizers (List[str], optional): Finalizers for the application set metadata.
        body_applicationSet_metadata_generateName (str, optional): Generate name for the application set metadata.
        body_applicationSet_metadata_generation (int, optional): Generation for the application set metadata.
        body_applicationSet_metadata_labels (Dict[str, Any], optional): Labels for the application set metadata.
        body_applicationSet_metadata_managedFields (List[str], optional): Managed fields for the application set metadata.
        body_applicationSet_metadata_name (str, optional): Name for the application set metadata.
        body_applicationSet_metadata_namespace (str, optional): Namespace for the application set metadata.
        body_applicationSet_metadata_ownerReferences (List[str], optional): Owner references for the application set metadata.
        body_applicationSet_metadata_resourceVersion (str, optional): Resource version for the application set metadata.
        body_applicationSet_metadata_selfLink (str, optional): Self link for the application set metadata.
        body_applicationSet_metadata_uid (str, optional): UID for the application set metadata.
        body_applicationSet_spec_applyNestedSelectors (bool, optional): Apply nested selectors for the application set spec.
        body_applicationSet_spec_generators (List[str], optional): Generators for the application set spec.
        body_applicationSet_spec_goTemplate (bool, optional): Go template for the application set spec.
        body_applicationSet_spec_goTemplateOptions (List[str], optional): Go template options for the application set spec.
        body_applicationSet_spec_ignoreApplicationDifferences (List[str], optional): Ignore application differences for the application set spec.
        body_applicationSet_spec_preservedFields_annotations (List[str], optional): Preserved fields annotations for the application set spec.
        body_applicationSet_spec_preservedFields_labels (List[str], optional): Preserved fields labels for the application set spec.
        body_applicationSet_spec_strategy_rollingSync_steps (List[str], optional): Rolling sync steps for the application set spec strategy.
        body_applicationSet_spec_strategy_type (str, optional): Strategy type for the application set spec.
        body_applicationSet_spec_syncPolicy_applicationsSync (str, optional): Applications sync policy for the application set spec.
        body_applicationSet_spec_syncPolicy_preserveResourcesOnDeletion (bool, optional): Preserve resources on deletion for the application set spec sync policy.
        body_applicationSet_spec_template_metadata_annotations (Dict[str, Any], optional): Annotations for the application set spec template metadata.
        body_applicationSet_spec_template_metadata_finalizers (List[str], optional): Finalizers for the application set spec template metadata.
        body_applicationSet_spec_template_metadata_labels (Dict[str, Any], optional): Labels for the application set spec template metadata.
        body_applicationSet_spec_template_metadata_name (str, optional): Name for the application set spec template metadata.
        body_applicationSet_spec_template_metadata_namespace (str, optional): Namespace for the application set spec template metadata.
        body_applicationSet_spec_template_spec_destination_name (str, optional): Destination name for the application set spec template.
        body_applicationSet_spec_template_spec_destination_namespace (str, optional): Destination namespace for the application set spec template.
        body_applicationSet_spec_template_spec_destination_server (str, optional): Destination server for the application set spec template.
        body_applicationSet_spec_template_spec_ignoreDifferences (List[str], optional): Ignore differences for the application set spec template.
        body_applicationSet_spec_template_spec_info (List[str], optional): Info for the application set spec template.
        body_applicationSet_spec_template_spec_project (str, optional): Project for the application set spec template.
        body_applicationSet_spec_template_spec_revisionHistoryLimit (int, optional): Revision history limit for the application set spec template.
        body_applicationSet_spec_template_spec_source_chart (str, optional): Source chart for the application set spec template.
        body_applicationSet_spec_template_spec_source_directory_exclude (str, optional): Source directory exclude for the application set spec template.
        body_applicationSet_spec_template_spec_source_directory_include (str, optional): Source directory include for the application set spec template.
        body_applicationSet_spec_template_spec_source_directory_jsonnet_extVars (List[str], optional): Source directory jsonnet extVars for the application set spec template.
        body_applicationSet_spec_template_spec_source_directory_jsonnet_libs (List[str], optional): Source directory jsonnet libs for the application set spec template.
        body_applicationSet_spec_template_spec_source_directory_jsonnet_tlas (List[str], optional): Source directory jsonnet tlas for the application set spec template.
        body_applicationSet_spec_template_spec_source_directory_recurse (bool, optional): Source directory recurse for the application set spec template.
        body_applicationSet_spec_template_spec_source_helm_apiVersions (List[str], optional): Source helm apiVersions for the application set spec template.
        body_applicationSet_spec_template_spec_source_helm_fileParameters (List[str], optional): Source helm fileParameters for the application set spec template.
        body_applicationSet_spec_template_spec_source_helm_ignoreMissingValueFiles (bool, optional): Source helm ignore missing value files for the application set spec template.
        body_applicationSet_spec_template_spec_source_helm_kubeVersion (str, optional): Source helm kubeVersion for the application set spec template.
        body_applicationSet_spec_template_spec_source_helm_namespace (str, optional): Source helm namespace for the application set spec template.
        body_applicationSet_spec_template_spec_source_helm_parameters (List[str], optional): Source helm parameters for the application set spec template.
        body_applicationSet_spec_template_spec_source_helm_passCredentials (bool, optional): Source helm pass credentials for the application set spec template.
        body_applicationSet_spec_template_spec_source_helm_releaseName (str, optional): Source helm release name for the application set spec template.
        body_applicationSet_spec_template_spec_source_helm_skipCrds (bool, optional): Source helm skip CRDs for the application set spec template.
        body_applicationSet_spec_template_spec_source_helm_skipSchemaValidation (bool, optional): Source helm skip schema validation for the application set spec template.
        body_applicationSet_spec_template_spec_source_helm_skipTests (bool, optional): Source helm skip tests for the application set spec template.
        body_applicationSet_spec_template_spec_source_helm_valueFiles (List[str], optional): Source helm value files for the application set spec template.
        body_applicationSet_spec_template_spec_source_helm_values (str, optional): Source helm values for the application set spec template.
        body_applicationSet_spec_template_spec_source_helm_valuesObject_raw (str, optional): Source helm values object raw for the application set spec template.
        body_applicationSet_spec_template_spec_source_helm_version (str, optional): Source helm version for the application set spec template.
        body_applicationSet_spec_template_spec_source_kustomize_apiVersions (List[str], optional): Source kustomize apiVersions for the application set spec template.
        body_applicationSet_spec_template_spec_source_kustomize_commonAnnotations (Dict[str, Any], optional): Source kustomize common annotations for the application set spec template.
        body_applicationSet_spec_template_spec_source_kustomize_commonAnnotationsEnvsubst (bool, optional): Source kustomize common annotations envsubst for the application set spec template.
        body_applicationSet_spec_template_spec_source_kustomize_commonLabels (Dict[str, Any], optional): Source kustomize common labels for the application set spec template.
        body_applicationSet_spec_template_spec_source_kustomize_components (List[str], optional): Source kustomize components for the application set spec template.
        body_applicationSet_spec_template_spec_source_kustomize_forceCommonAnnotations (bool, optional): Source kustomize force common annotations for the application set spec template.
        body_applicationSet_spec_template_spec_source_kustomize_forceCommonLabels (bool, optional): Source kustomize force common labels for the application set spec template.
        body_applicationSet_spec_template_spec_source_kustomize_ignoreMissingComponents (bool, optional): Source kustomize ignore missing components for the application set spec template.
        body_applicationSet_spec_template_spec_source_kustomize_images (List[str], optional): Source kustomize images for the application set spec template.
        body_applicationSet_spec_template_spec_source_kustomize_kubeVersion (str, optional): Source kustomize kubeVersion for the application set spec template.
        body_applicationSet_spec_template_spec_source_kustomize_labelIncludeTemplates (bool, optional): Source kustomize label include templates for the application set spec template.
        body_applicationSet_spec_template_spec_source_kustomize_labelWithoutSelector (bool, optional): Source kustomize label without selector for the application set spec template.
        body_applicationSet_spec_template_spec_source_kustomize_namePrefix (str, optional): Source kustomize name prefix for the application set spec template.
        body_applicationSet_spec_template_spec_source_kustomize_nameSuffix (str, optional): Source kustomize name suffix for the application set spec template.
        body_applicationSet_spec_template_spec_source_kustomize_namespace (str, optional): Source kustomize namespace for the application set spec template.
        body_applicationSet_spec_template_spec_source_kustomize_patches (List[str], optional): Source kustomize patches for the application set spec template.
        body_applicationSet_spec_template_spec_source_kustomize_replicas (List[str], optional): Source kustomize replicas for the application set spec template.
        body_applicationSet_spec_template_spec_source_kustomize_version (str, optional): Source kustomize version for the application set spec template.
        body_applicationSet_spec_template_spec_source_name (str, optional): Source name for the application set spec template.
        body_applicationSet_spec_template_spec_source_path (str, optional): Source path for the application set spec template.
        body_applicationSet_spec_template_spec_source_plugin_env (List[str], optional): Source plugin environment for the application set spec template.
        body_applicationSet_spec_template_spec_source_plugin_name (str, optional): Source plugin name for the application set spec template.
        body_applicationSet_spec_template_spec_source_plugin_parameters (List[str], optional): Source plugin parameters for the application set spec template.
        body_applicationSet_spec_template_spec_source_ref (str, optional): Source reference for the application set spec template.
        body_applicationSet_spec_template_spec_source_repoURL (str, optional): Source repository URL for the application set spec template.
        body_applicationSet_spec_template_spec_source_targetRevision (str, optional): Source target revision for the application set spec template.
        body_applicationSet_spec_template_spec_sourceHydrator_drySource_path (str, optional): Source hydrator dry source path for the application set spec template.
        body_applicationSet_spec_template_spec_sourceHydrator_drySource_repoURL (str, optional): Source hydrator dry source repository URL for the application set spec template.
        body_applicationSet_spec_template_spec_sourceHydrator_drySource_targetRevision (str, optional): Source hydrator dry source target revision for the application set spec template.
        body_applicationSet_spec_template_spec_sourceHydrator_hydrateTo_targetBranch (str, optional): Source hydrator hydrate to target branch for the application set spec template.
        body_applicationSet_spec_template_spec_sourceHydrator_syncSource_path (str, optional): Source hydrator sync source path for the application set spec template.
        body_applicationSet_spec_template_spec_sourceHydrator_syncSource_targetBranch (str, optional): Source hydrator sync source target branch for the application set spec template.
        body_applicationSet_spec_template_spec_sources (List[str], optional): Sources for the application set spec template.
        body_applicationSet_spec_template_spec_syncPolicy_automated_allowEmpty (bool, optional): Automated sync policy allow empty for the application set spec template.
        body_applicationSet_spec_template_spec_syncPolicy_automated_enable (bool, optional): Automated sync policy enable for the application set spec template.
        body_applicationSet_spec_template_spec_syncPolicy_automated_prune (bool, optional): Automated sync policy prune for the application set spec template.
        body_applicationSet_spec_template_spec_syncPolicy_automated_selfHeal (bool, optional): Automated sync policy self-heal for the application set spec template.
        body_applicationSet_spec_template_spec_syncPolicy_managedNamespaceMetadata_annotations (Dict[str, Any], optional): Managed namespace metadata annotations for the application set spec template sync policy.
        body_applicationSet_spec_template_spec_syncPolicy_managedNamespaceMetadata_labels (Dict[str, Any], optional): Managed namespace metadata labels for the application set spec template sync policy.
        body_applicationSet_spec_template_spec_syncPolicy_retry_backoff_duration (str, optional): Retry backoff duration for the application set spec template sync policy.
        body_applicationSet_spec_template_spec_syncPolicy_retry_backoff_factor (int, optional): Retry backoff factor for the application set spec template sync policy.
        body_applicationSet_spec_template_spec_syncPolicy_retry_backoff_maxDuration (str, optional): Retry backoff max duration for the application set spec template sync policy.
        body_applicationSet_spec_template_spec_syncPolicy_retry_limit (int, optional): Retry limit for the application set spec template sync policy.
        body_applicationSet_spec_template_spec_syncPolicy_syncOptions (List[str], optional): Sync options for the application set spec template sync policy.
        body_applicationSet_spec_templatePatch (str, optional): Template patch for the application set spec.
        body_applicationSet_status_applicationStatus (List[str], optional): Application status for the application set status.
        body_applicationSet_status_conditions (List[str], optional): Conditions for the application set status.
        body_applicationSet_status_resources (List[str], optional): Resources for the application set status.

    Returns:
        Dict[str, Any]: The JSON response from the API call.

    Raises:
        Exception: If the API request fails or returns an error.
    '''
    logger.debug("Making POST request to /api/v1/applicationsets/generate")

    params = {}
    data = {}

    flat_body = {}
    if body_applicationSet_metadata_annotations is not None:
        flat_body["applicationSet_metadata_annotations"] = body_applicationSet_metadata_annotations
    if body_applicationSet_metadata_creationTimestamp is not None:
        flat_body["applicationSet_metadata_creationTimestamp"] = body_applicationSet_metadata_creationTimestamp
    if body_applicationSet_metadata_deletionGracePeriodSeconds is not None:
        flat_body["applicationSet_metadata_deletionGracePeriodSeconds"] = (
            body_applicationSet_metadata_deletionGracePeriodSeconds
        )
    if body_applicationSet_metadata_deletionTimestamp is not None:
        flat_body["applicationSet_metadata_deletionTimestamp"] = body_applicationSet_metadata_deletionTimestamp
    if body_applicationSet_metadata_finalizers is not None:
        flat_body["applicationSet_metadata_finalizers"] = body_applicationSet_metadata_finalizers
    if body_applicationSet_metadata_generateName is not None:
        flat_body["applicationSet_metadata_generateName"] = body_applicationSet_metadata_generateName
    if body_applicationSet_metadata_generation is not None:
        flat_body["applicationSet_metadata_generation"] = body_applicationSet_metadata_generation
    if body_applicationSet_metadata_labels is not None:
        flat_body["applicationSet_metadata_labels"] = body_applicationSet_metadata_labels
    if body_applicationSet_metadata_managedFields is not None:
        flat_body["applicationSet_metadata_managedFields"] = body_applicationSet_metadata_managedFields
    if body_applicationSet_metadata_name is not None:
        flat_body["applicationSet_metadata_name"] = body_applicationSet_metadata_name
    if body_applicationSet_metadata_namespace is not None:
        flat_body["applicationSet_metadata_namespace"] = body_applicationSet_metadata_namespace
    if body_applicationSet_metadata_ownerReferences is not None:
        flat_body["applicationSet_metadata_ownerReferences"] = body_applicationSet_metadata_ownerReferences
    if body_applicationSet_metadata_resourceVersion is not None:
        flat_body["applicationSet_metadata_resourceVersion"] = body_applicationSet_metadata_resourceVersion
    if body_applicationSet_metadata_selfLink is not None:
        flat_body["applicationSet_metadata_selfLink"] = body_applicationSet_metadata_selfLink
    if body_applicationSet_metadata_uid is not None:
        flat_body["applicationSet_metadata_uid"] = body_applicationSet_metadata_uid
    if body_applicationSet_spec_applyNestedSelectors is not None:
        flat_body["applicationSet_spec_applyNestedSelectors"] = body_applicationSet_spec_applyNestedSelectors
    if body_applicationSet_spec_generators is not None:
        flat_body["applicationSet_spec_generators"] = body_applicationSet_spec_generators
    if body_applicationSet_spec_goTemplate is not None:
        flat_body["applicationSet_spec_goTemplate"] = body_applicationSet_spec_goTemplate
    if body_applicationSet_spec_goTemplateOptions is not None:
        flat_body["applicationSet_spec_goTemplateOptions"] = body_applicationSet_spec_goTemplateOptions
    if body_applicationSet_spec_ignoreApplicationDifferences is not None:
        flat_body["applicationSet_spec_ignoreApplicationDifferences"] = (
            body_applicationSet_spec_ignoreApplicationDifferences
        )
    if body_applicationSet_spec_preservedFields_annotations is not None:
        flat_body["applicationSet_spec_preservedFields_annotations"] = (
            body_applicationSet_spec_preservedFields_annotations
        )
    if body_applicationSet_spec_preservedFields_labels is not None:
        flat_body["applicationSet_spec_preservedFields_labels"] = body_applicationSet_spec_preservedFields_labels
    if body_applicationSet_spec_strategy_rollingSync_steps is not None:
        flat_body["applicationSet_spec_strategy_rollingSync_steps"] = (
            body_applicationSet_spec_strategy_rollingSync_steps
        )
    if body_applicationSet_spec_strategy_type is not None:
        flat_body["applicationSet_spec_strategy_type"] = body_applicationSet_spec_strategy_type
    if body_applicationSet_spec_syncPolicy_applicationsSync is not None:
        flat_body["applicationSet_spec_syncPolicy_applicationsSync"] = (
            body_applicationSet_spec_syncPolicy_applicationsSync
        )
    if body_applicationSet_spec_syncPolicy_preserveResourcesOnDeletion is not None:
        flat_body["applicationSet_spec_syncPolicy_preserveResourcesOnDeletion"] = (
            body_applicationSet_spec_syncPolicy_preserveResourcesOnDeletion
        )
    if body_applicationSet_spec_template_metadata_annotations is not None:
        flat_body["applicationSet_spec_template_metadata_annotations"] = (
            body_applicationSet_spec_template_metadata_annotations
        )
    if body_applicationSet_spec_template_metadata_finalizers is not None:
        flat_body["applicationSet_spec_template_metadata_finalizers"] = (
            body_applicationSet_spec_template_metadata_finalizers
        )
    if body_applicationSet_spec_template_metadata_labels is not None:
        flat_body["applicationSet_spec_template_metadata_labels"] = body_applicationSet_spec_template_metadata_labels
    if body_applicationSet_spec_template_metadata_name is not None:
        flat_body["applicationSet_spec_template_metadata_name"] = body_applicationSet_spec_template_metadata_name
    if body_applicationSet_spec_template_metadata_namespace is not None:
        flat_body["applicationSet_spec_template_metadata_namespace"] = (
            body_applicationSet_spec_template_metadata_namespace
        )
    if body_applicationSet_spec_template_spec_destination_name is not None:
        flat_body["applicationSet_spec_template_spec_destination_name"] = (
            body_applicationSet_spec_template_spec_destination_name
        )
    if body_applicationSet_spec_template_spec_destination_namespace is not None:
        flat_body["applicationSet_spec_template_spec_destination_namespace"] = (
            body_applicationSet_spec_template_spec_destination_namespace
        )
    if body_applicationSet_spec_template_spec_destination_server is not None:
        flat_body["applicationSet_spec_template_spec_destination_server"] = (
            body_applicationSet_spec_template_spec_destination_server
        )
    if body_applicationSet_spec_template_spec_ignoreDifferences is not None:
        flat_body["applicationSet_spec_template_spec_ignoreDifferences"] = (
            body_applicationSet_spec_template_spec_ignoreDifferences
        )
    if body_applicationSet_spec_template_spec_info is not None:
        flat_body["applicationSet_spec_template_spec_info"] = body_applicationSet_spec_template_spec_info
    if body_applicationSet_spec_template_spec_project is not None:
        flat_body["applicationSet_spec_template_spec_project"] = body_applicationSet_spec_template_spec_project
    if body_applicationSet_spec_template_spec_revisionHistoryLimit is not None:
        flat_body["applicationSet_spec_template_spec_revisionHistoryLimit"] = (
            body_applicationSet_spec_template_spec_revisionHistoryLimit
        )
    if body_applicationSet_spec_template_spec_source_chart is not None:
        flat_body["applicationSet_spec_template_spec_source_chart"] = (
            body_applicationSet_spec_template_spec_source_chart
        )
    if body_applicationSet_spec_template_spec_source_directory_exclude is not None:
        flat_body["applicationSet_spec_template_spec_source_directory_exclude"] = (
            body_applicationSet_spec_template_spec_source_directory_exclude
        )
    if body_applicationSet_spec_template_spec_source_directory_include is not None:
        flat_body["applicationSet_spec_template_spec_source_directory_include"] = (
            body_applicationSet_spec_template_spec_source_directory_include
        )
    if body_applicationSet_spec_template_spec_source_directory_jsonnet_extVars is not None:
        flat_body["applicationSet_spec_template_spec_source_directory_jsonnet_extVars"] = (
            body_applicationSet_spec_template_spec_source_directory_jsonnet_extVars
        )
    if body_applicationSet_spec_template_spec_source_directory_jsonnet_libs is not None:
        flat_body["applicationSet_spec_template_spec_source_directory_jsonnet_libs"] = (
            body_applicationSet_spec_template_spec_source_directory_jsonnet_libs
        )
    if body_applicationSet_spec_template_spec_source_directory_jsonnet_tlas is not None:
        flat_body["applicationSet_spec_template_spec_source_directory_jsonnet_tlas"] = (
            body_applicationSet_spec_template_spec_source_directory_jsonnet_tlas
        )
    if body_applicationSet_spec_template_spec_source_directory_recurse is not None:
        flat_body["applicationSet_spec_template_spec_source_directory_recurse"] = (
            body_applicationSet_spec_template_spec_source_directory_recurse
        )
    if body_applicationSet_spec_template_spec_source_helm_apiVersions is not None:
        flat_body["applicationSet_spec_template_spec_source_helm_apiVersions"] = (
            body_applicationSet_spec_template_spec_source_helm_apiVersions
        )
    if body_applicationSet_spec_template_spec_source_helm_fileParameters is not None:
        flat_body["applicationSet_spec_template_spec_source_helm_fileParameters"] = (
            body_applicationSet_spec_template_spec_source_helm_fileParameters
        )
    if body_applicationSet_spec_template_spec_source_helm_ignoreMissingValueFiles is not None:
        flat_body["applicationSet_spec_template_spec_source_helm_ignoreMissingValueFiles"] = (
            body_applicationSet_spec_template_spec_source_helm_ignoreMissingValueFiles
        )
    if body_applicationSet_spec_template_spec_source_helm_kubeVersion is not None:
        flat_body["applicationSet_spec_template_spec_source_helm_kubeVersion"] = (
            body_applicationSet_spec_template_spec_source_helm_kubeVersion
        )
    if body_applicationSet_spec_template_spec_source_helm_namespace is not None:
        flat_body["applicationSet_spec_template_spec_source_helm_namespace"] = (
            body_applicationSet_spec_template_spec_source_helm_namespace
        )
    if body_applicationSet_spec_template_spec_source_helm_parameters is not None:
        flat_body["applicationSet_spec_template_spec_source_helm_parameters"] = (
            body_applicationSet_spec_template_spec_source_helm_parameters
        )
    if body_applicationSet_spec_template_spec_source_helm_passCredentials is not None:
        flat_body["applicationSet_spec_template_spec_source_helm_passCredentials"] = (
            body_applicationSet_spec_template_spec_source_helm_passCredentials
        )
    if body_applicationSet_spec_template_spec_source_helm_releaseName is not None:
        flat_body["applicationSet_spec_template_spec_source_helm_releaseName"] = (
            body_applicationSet_spec_template_spec_source_helm_releaseName
        )
    if body_applicationSet_spec_template_spec_source_helm_skipCrds is not None:
        flat_body["applicationSet_spec_template_spec_source_helm_skipCrds"] = (
            body_applicationSet_spec_template_spec_source_helm_skipCrds
        )
    if body_applicationSet_spec_template_spec_source_helm_skipSchemaValidation is not None:
        flat_body["applicationSet_spec_template_spec_source_helm_skipSchemaValidation"] = (
            body_applicationSet_spec_template_spec_source_helm_skipSchemaValidation
        )
    if body_applicationSet_spec_template_spec_source_helm_skipTests is not None:
        flat_body["applicationSet_spec_template_spec_source_helm_skipTests"] = (
            body_applicationSet_spec_template_spec_source_helm_skipTests
        )
    if body_applicationSet_spec_template_spec_source_helm_valueFiles is not None:
        flat_body["applicationSet_spec_template_spec_source_helm_valueFiles"] = (
            body_applicationSet_spec_template_spec_source_helm_valueFiles
        )
    if body_applicationSet_spec_template_spec_source_helm_values is not None:
        flat_body["applicationSet_spec_template_spec_source_helm_values"] = (
            body_applicationSet_spec_template_spec_source_helm_values
        )
    if body_applicationSet_spec_template_spec_source_helm_valuesObject_raw is not None:
        flat_body["applicationSet_spec_template_spec_source_helm_valuesObject_raw"] = (
            body_applicationSet_spec_template_spec_source_helm_valuesObject_raw
        )
    if body_applicationSet_spec_template_spec_source_helm_version is not None:
        flat_body["applicationSet_spec_template_spec_source_helm_version"] = (
            body_applicationSet_spec_template_spec_source_helm_version
        )
    if body_applicationSet_spec_template_spec_source_kustomize_apiVersions is not None:
        flat_body["applicationSet_spec_template_spec_source_kustomize_apiVersions"] = (
            body_applicationSet_spec_template_spec_source_kustomize_apiVersions
        )
    if body_applicationSet_spec_template_spec_source_kustomize_commonAnnotations is not None:
        flat_body["applicationSet_spec_template_spec_source_kustomize_commonAnnotations"] = (
            body_applicationSet_spec_template_spec_source_kustomize_commonAnnotations
        )
    if body_applicationSet_spec_template_spec_source_kustomize_commonAnnotationsEnvsubst is not None:
        flat_body["applicationSet_spec_template_spec_source_kustomize_commonAnnotationsEnvsubst"] = (
            body_applicationSet_spec_template_spec_source_kustomize_commonAnnotationsEnvsubst
        )
    if body_applicationSet_spec_template_spec_source_kustomize_commonLabels is not None:
        flat_body["applicationSet_spec_template_spec_source_kustomize_commonLabels"] = (
            body_applicationSet_spec_template_spec_source_kustomize_commonLabels
        )
    if body_applicationSet_spec_template_spec_source_kustomize_components is not None:
        flat_body["applicationSet_spec_template_spec_source_kustomize_components"] = (
            body_applicationSet_spec_template_spec_source_kustomize_components
        )
    if body_applicationSet_spec_template_spec_source_kustomize_forceCommonAnnotations is not None:
        flat_body["applicationSet_spec_template_spec_source_kustomize_forceCommonAnnotations"] = (
            body_applicationSet_spec_template_spec_source_kustomize_forceCommonAnnotations
        )
    if body_applicationSet_spec_template_spec_source_kustomize_forceCommonLabels is not None:
        flat_body["applicationSet_spec_template_spec_source_kustomize_forceCommonLabels"] = (
            body_applicationSet_spec_template_spec_source_kustomize_forceCommonLabels
        )
    if body_applicationSet_spec_template_spec_source_kustomize_ignoreMissingComponents is not None:
        flat_body["applicationSet_spec_template_spec_source_kustomize_ignoreMissingComponents"] = (
            body_applicationSet_spec_template_spec_source_kustomize_ignoreMissingComponents
        )
    if body_applicationSet_spec_template_spec_source_kustomize_images is not None:
        flat_body["applicationSet_spec_template_spec_source_kustomize_images"] = (
            body_applicationSet_spec_template_spec_source_kustomize_images
        )
    if body_applicationSet_spec_template_spec_source_kustomize_kubeVersion is not None:
        flat_body["applicationSet_spec_template_spec_source_kustomize_kubeVersion"] = (
            body_applicationSet_spec_template_spec_source_kustomize_kubeVersion
        )
    if body_applicationSet_spec_template_spec_source_kustomize_labelIncludeTemplates is not None:
        flat_body["applicationSet_spec_template_spec_source_kustomize_labelIncludeTemplates"] = (
            body_applicationSet_spec_template_spec_source_kustomize_labelIncludeTemplates
        )
    if body_applicationSet_spec_template_spec_source_kustomize_labelWithoutSelector is not None:
        flat_body["applicationSet_spec_template_spec_source_kustomize_labelWithoutSelector"] = (
            body_applicationSet_spec_template_spec_source_kustomize_labelWithoutSelector
        )
    if body_applicationSet_spec_template_spec_source_kustomize_namePrefix is not None:
        flat_body["applicationSet_spec_template_spec_source_kustomize_namePrefix"] = (
            body_applicationSet_spec_template_spec_source_kustomize_namePrefix
        )
    if body_applicationSet_spec_template_spec_source_kustomize_nameSuffix is not None:
        flat_body["applicationSet_spec_template_spec_source_kustomize_nameSuffix"] = (
            body_applicationSet_spec_template_spec_source_kustomize_nameSuffix
        )
    if body_applicationSet_spec_template_spec_source_kustomize_namespace is not None:
        flat_body["applicationSet_spec_template_spec_source_kustomize_namespace"] = (
            body_applicationSet_spec_template_spec_source_kustomize_namespace
        )
    if body_applicationSet_spec_template_spec_source_kustomize_patches is not None:
        flat_body["applicationSet_spec_template_spec_source_kustomize_patches"] = (
            body_applicationSet_spec_template_spec_source_kustomize_patches
        )
    if body_applicationSet_spec_template_spec_source_kustomize_replicas is not None:
        flat_body["applicationSet_spec_template_spec_source_kustomize_replicas"] = (
            body_applicationSet_spec_template_spec_source_kustomize_replicas
        )
    if body_applicationSet_spec_template_spec_source_kustomize_version is not None:
        flat_body["applicationSet_spec_template_spec_source_kustomize_version"] = (
            body_applicationSet_spec_template_spec_source_kustomize_version
        )
    if body_applicationSet_spec_template_spec_source_name is not None:
        flat_body["applicationSet_spec_template_spec_source_name"] = body_applicationSet_spec_template_spec_source_name
    if body_applicationSet_spec_template_spec_source_path is not None:
        flat_body["applicationSet_spec_template_spec_source_path"] = body_applicationSet_spec_template_spec_source_path
    if body_applicationSet_spec_template_spec_source_plugin_env is not None:
        flat_body["applicationSet_spec_template_spec_source_plugin_env"] = (
            body_applicationSet_spec_template_spec_source_plugin_env
        )
    if body_applicationSet_spec_template_spec_source_plugin_name is not None:
        flat_body["applicationSet_spec_template_spec_source_plugin_name"] = (
            body_applicationSet_spec_template_spec_source_plugin_name
        )
    if body_applicationSet_spec_template_spec_source_plugin_parameters is not None:
        flat_body["applicationSet_spec_template_spec_source_plugin_parameters"] = (
            body_applicationSet_spec_template_spec_source_plugin_parameters
        )
    if body_applicationSet_spec_template_spec_source_ref is not None:
        flat_body["applicationSet_spec_template_spec_source_ref"] = body_applicationSet_spec_template_spec_source_ref
    if body_applicationSet_spec_template_spec_source_repoURL is not None:
        flat_body["applicationSet_spec_template_spec_source_repoURL"] = (
            body_applicationSet_spec_template_spec_source_repoURL
        )
    if body_applicationSet_spec_template_spec_source_targetRevision is not None:
        flat_body["applicationSet_spec_template_spec_source_targetRevision"] = (
            body_applicationSet_spec_template_spec_source_targetRevision
        )
    if body_applicationSet_spec_template_spec_sourceHydrator_drySource_path is not None:
        flat_body["applicationSet_spec_template_spec_sourceHydrator_drySource_path"] = (
            body_applicationSet_spec_template_spec_sourceHydrator_drySource_path
        )
    if body_applicationSet_spec_template_spec_sourceHydrator_drySource_repoURL is not None:
        flat_body["applicationSet_spec_template_spec_sourceHydrator_drySource_repoURL"] = (
            body_applicationSet_spec_template_spec_sourceHydrator_drySource_repoURL
        )
    if body_applicationSet_spec_template_spec_sourceHydrator_drySource_targetRevision is not None:
        flat_body["applicationSet_spec_template_spec_sourceHydrator_drySource_targetRevision"] = (
            body_applicationSet_spec_template_spec_sourceHydrator_drySource_targetRevision
        )
    if body_applicationSet_spec_template_spec_sourceHydrator_hydrateTo_targetBranch is not None:
        flat_body["applicationSet_spec_template_spec_sourceHydrator_hydrateTo_targetBranch"] = (
            body_applicationSet_spec_template_spec_sourceHydrator_hydrateTo_targetBranch
        )
    if body_applicationSet_spec_template_spec_sourceHydrator_syncSource_path is not None:
        flat_body["applicationSet_spec_template_spec_sourceHydrator_syncSource_path"] = (
            body_applicationSet_spec_template_spec_sourceHydrator_syncSource_path
        )
    if body_applicationSet_spec_template_spec_sourceHydrator_syncSource_targetBranch is not None:
        flat_body["applicationSet_spec_template_spec_sourceHydrator_syncSource_targetBranch"] = (
            body_applicationSet_spec_template_spec_sourceHydrator_syncSource_targetBranch
        )
    if body_applicationSet_spec_template_spec_sources is not None:
        flat_body["applicationSet_spec_template_spec_sources"] = body_applicationSet_spec_template_spec_sources
    if body_applicationSet_spec_template_spec_syncPolicy_automated_allowEmpty is not None:
        flat_body["applicationSet_spec_template_spec_syncPolicy_automated_allowEmpty"] = (
            body_applicationSet_spec_template_spec_syncPolicy_automated_allowEmpty
        )
    if body_applicationSet_spec_template_spec_syncPolicy_automated_enable is not None:
        flat_body["applicationSet_spec_template_spec_syncPolicy_automated_enable"] = (
            body_applicationSet_spec_template_spec_syncPolicy_automated_enable
        )
    if body_applicationSet_spec_template_spec_syncPolicy_automated_prune is not None:
        flat_body["applicationSet_spec_template_spec_syncPolicy_automated_prune"] = (
            body_applicationSet_spec_template_spec_syncPolicy_automated_prune
        )
    if body_applicationSet_spec_template_spec_syncPolicy_automated_selfHeal is not None:
        flat_body["applicationSet_spec_template_spec_syncPolicy_automated_selfHeal"] = (
            body_applicationSet_spec_template_spec_syncPolicy_automated_selfHeal
        )
    if body_applicationSet_spec_template_spec_syncPolicy_managedNamespaceMetadata_annotations is not None:
        flat_body["applicationSet_spec_template_spec_syncPolicy_managedNamespaceMetadata_annotations"] = (
            body_applicationSet_spec_template_spec_syncPolicy_managedNamespaceMetadata_annotations
        )
    if body_applicationSet_spec_template_spec_syncPolicy_managedNamespaceMetadata_labels is not None:
        flat_body["applicationSet_spec_template_spec_syncPolicy_managedNamespaceMetadata_labels"] = (
            body_applicationSet_spec_template_spec_syncPolicy_managedNamespaceMetadata_labels
        )
    if body_applicationSet_spec_template_spec_syncPolicy_retry_backoff_duration is not None:
        flat_body["applicationSet_spec_template_spec_syncPolicy_retry_backoff_duration"] = (
            body_applicationSet_spec_template_spec_syncPolicy_retry_backoff_duration
        )
    if body_applicationSet_spec_template_spec_syncPolicy_retry_backoff_factor is not None:
        flat_body["applicationSet_spec_template_spec_syncPolicy_retry_backoff_factor"] = (
            body_applicationSet_spec_template_spec_syncPolicy_retry_backoff_factor
        )
    if body_applicationSet_spec_template_spec_syncPolicy_retry_backoff_maxDuration is not None:
        flat_body["applicationSet_spec_template_spec_syncPolicy_retry_backoff_maxDuration"] = (
            body_applicationSet_spec_template_spec_syncPolicy_retry_backoff_maxDuration
        )
    if body_applicationSet_spec_template_spec_syncPolicy_retry_limit is not None:
        flat_body["applicationSet_spec_template_spec_syncPolicy_retry_limit"] = (
            body_applicationSet_spec_template_spec_syncPolicy_retry_limit
        )
    if body_applicationSet_spec_template_spec_syncPolicy_syncOptions is not None:
        flat_body["applicationSet_spec_template_spec_syncPolicy_syncOptions"] = (
            body_applicationSet_spec_template_spec_syncPolicy_syncOptions
        )
    if body_applicationSet_spec_templatePatch is not None:
        flat_body["applicationSet_spec_templatePatch"] = body_applicationSet_spec_templatePatch
    if body_applicationSet_status_applicationStatus is not None:
        flat_body["applicationSet_status_applicationStatus"] = body_applicationSet_status_applicationStatus
    if body_applicationSet_status_conditions is not None:
        flat_body["applicationSet_status_conditions"] = body_applicationSet_status_conditions
    if body_applicationSet_status_resources is not None:
        flat_body["applicationSet_status_resources"] = body_applicationSet_status_resources
    data = assemble_nested_body(flat_body)

    success, response = await make_api_request(
        "/api/v1/applicationsets/generate", method="POST", params=params, data=data
    )

    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get("error", "Request failed")}
    return response