
# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /api/v1/repocreds operations"""

import logging
from typing import Dict, Any
from agent_argocd.protocol_bindings.mcp_server.mcp_argocd.api.client import make_api_request

# Configure logging
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger("mcp_tools")


async def repocredsservice_listrepositorycredentials(url: str = None) -> Dict[str, Any]:
    '''
    Retrieves a list of all configured repository credential sets.

    Args:
        url (str, optional): The repository URL to filter credentials by. Defaults to None.

    Returns:
        Dict[str, Any]: A dictionary containing the list of repository credential sets or an error message.

    Raises:
        Exception: If the API request fails or an unexpected error occurs.
    '''
    logger.debug("Making GET request to /api/v1/repocreds")
    params = {}
    
    if url is not None:
      params["url"] = url
    
    data = None

    success, response = await make_api_request(
        "/api/v1/repocreds",
        method="GET",
        params=params,
        data=data
    )
    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get('error', 'Request failed')}
    return response


async def repocredsservice_createrepositorycredentials(body: str, upsert: str = None) -> Dict[str, Any]:
    '''
    Creates a new repository credential set.

    Args:
        body (str): The JSON-encoded body containing repository credential details.
        upsert (str, optional): If set, allows updating existing credentials. Defaults to None.

    Returns:
        Dict[str, Any]: The response from the API containing the created or updated repository credentials.

    Raises:
        Exception: If the API request fails or returns an error.
    '''
    logger.debug("Making POST request to /api/v1/repocreds")
    params = {}
    
    if body is not None:
      params["body"] = body
    
    if upsert is not None:
      params["upsert"] = upsert
    
    data = None

    # Add parameters to request
    if body is not None:
        data = body

    success, response = await make_api_request(
        "/api/v1/repocreds",
        method="POST",
        params=params,
        data=data
    )
    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get('error', 'Request failed')}
    return response
