
# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /api/v1/projects operations"""

import logging
from typing import Dict, Any
from agent_argocd.protocol_bindings.mcp_server.mcp_argocd.api.client import make_api_request

# Configure logging
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger("mcp_tools")


async def projectservice_list(name: str = None) -> Dict[str, Any]:
    '''
    Retrieves a list of projects, optionally filtered by project name.

    Args:
        name (str, optional): The name of the project to filter results by. Defaults to None.

    Returns:
        Dict[str, Any]: A dictionary containing the list of projects or an error message.

    Raises:
        Exception: If the API request fails or an unexpected error occurs.
    '''
    logger.debug("Making GET request to /api/v1/projects")
    params = {}
    
    if name is not None:
      params["name"] = name
    
    data = None

    success, response = await make_api_request(
        "/api/v1/projects",
        method="GET",
        params=params,
        data=data
    )
    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get('error', 'Request failed')}
    return response


async def projectservice_create(body: str) -> Dict[str, Any]:
    '''
    Creates a new project.

    Args:
        body (str): The JSON-formatted string containing the project details.

    Returns:
        Dict[str, Any]: The response from the API containing the created project details or an error message.

    Raises:
        Exception: If the API request fails due to network issues or invalid input.
    '''
    logger.debug("Making POST request to /api/v1/projects")
    params = {}
    
    if body is not None:
      params["body"] = body
    
    data = None

    # Add parameters to request
    if body is not None:
        data = body

    success, response = await make_api_request(
        "/api/v1/projects",
        method="POST",
        params=params,
        data=data
    )
    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get('error', 'Request failed')}
    return response
