# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /api/v1/applications/{name}/links operations"""

import logging
from typing import Dict, Any
from agent_argocd.protocol_bindings.mcp_server.mcp_argocd.api.client import make_api_request


def assemble_nested_body(flat_body: Dict[str, Any]) -> Dict[str, Any]:
    '''
    Convert a flat dictionary with underscore-separated keys into a nested dictionary.

    Args:
        flat_body (Dict[str, Any]): A dictionary where keys are underscore-separated strings representing nested paths.

    Returns:
        Dict[str, Any]: A nested dictionary constructed from the flat dictionary.

    Raises:
        ValueError: If the input dictionary contains keys that cannot be split into valid parts.
    '''
    nested = {}
    for key, value in flat_body.items():
        parts = key.split("_")
        d = nested
        for part in parts[:-1]:
            d = d.setdefault(part, {})
        d[parts[-1]] = value
    return nested


# Configure logging
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger("mcp_tools")


async def application_service__list_links(
    path_name: str, param_namespace: str = None, param_project: str = None
) -> Dict[str, Any]:
    '''
    ListLinks returns the list of all application deep links.

    Args:
        path_name (str): The name of the application path for which links are to be listed.
        param_namespace (str, optional): The namespace parameter for filtering links. Defaults to None.
        param_project (str, optional): The project parameter for filtering links. Defaults to None.

    Returns:
        Dict[str, Any]: The JSON response from the API call containing the list of application deep links.

    Raises:
        Exception: If the API request fails or returns an error.
    '''
    logger.debug("Making GET request to /api/v1/applications/{name}/links")

    params = {}
    data = {}

    params["namespace"] = str(param_namespace).lower() if isinstance(param_namespace, bool) else param_namespace

    params["project"] = str(param_project).lower() if isinstance(param_project, bool) else param_project

    flat_body = {}
    data = assemble_nested_body(flat_body)

    success, response = await make_api_request(
        f"/api/v1/applications/{path_name}/links", method="GET", params=params, data=data
    )

    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get("error", "Request failed")}
    return response