# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /api/v1/applicationsets/{name} operations"""

import logging
from typing import Dict, Any
from agent_argocd.protocol_bindings.mcp_server.mcp_argocd.api.client import make_api_request, assemble_nested_body

# Configure logging
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger("mcp_tools")


async def application_set_service__get(path_name: str, param_appsetNamespace: str = None) -> Dict[str, Any]:
    '''
    Get an applicationset by name.

    Args:
        path_name (str): The name of the applicationset.
        param_appsetNamespace (str, optional): The application set namespace. Defaults to None, which uses the ArgoCD control plane namespace.

    Returns:
        Dict[str, Any]: The JSON response from the API call containing the applicationset details.

    Raises:
        Exception: If the API request fails or returns an error.
    '''
    logger.debug("Making GET request to /api/v1/applicationsets/{name}")

    params = {}
    data = {}

    if param_appsetNamespace is not None:
        params["appsetNamespace"] = (
            str(param_appsetNamespace).lower() if isinstance(param_appsetNamespace, bool) else param_appsetNamespace
        )

    flat_body = {}
    data = assemble_nested_body(flat_body)

    success, response = await make_api_request(
        f"/api/v1/applicationsets/{path_name}", method="GET", params=params, data=data
    )

    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get("error", "Request failed")}
    return response


async def application_set_service__delete(path_name: str, param_appsetNamespace: str = None) -> Dict[str, Any]:
    '''
    Delete an application set.

    Args:
        path_name (str): The name of the application set to delete.
        param_appsetNamespace (str, optional): The namespace of the application set. Defaults to the ArgoCD control plane namespace if not specified.

    Returns:
        Dict[str, Any]: The JSON response from the API call, containing the result of the delete operation.

    Raises:
        Exception: If the API request fails or returns an error.
    '''
    logger.debug("Making DELETE request to /api/v1/applicationsets/{name}")

    params = {}
    data = {}

    if param_appsetNamespace is not None:
        params["appsetNamespace"] = (
            str(param_appsetNamespace).lower() if isinstance(param_appsetNamespace, bool) else param_appsetNamespace
        )

    flat_body = {}
    data = assemble_nested_body(flat_body)

    success, response = await make_api_request(
        f"/api/v1/applicationsets/{path_name}", method="DELETE", params=params, data=data
    )

    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get("error", "Request failed")}
    return response