
# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

#!/usr/bin/env python3
"""
 MCP Server

This server provides a Model Context Protocol (MCP) interface to the ,
allowing large language models and AI assistants to interact with the service.
"""
import logging
import os
from dotenv import load_dotenv
from mcp.server.fastmcp import FastMCP

# Load environment variables first
load_dotenv()

'''from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import admin_key

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import attachments

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import attachments_id

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import attachments_id_labels

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import attachments_id_operations

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import attachments_attachment_id_properties

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import attachments_attachment_id_properties_property_id

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import attachments_id_versions

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import attachments_attachment_id_versions_version_number

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import attachments_id_footer_comments

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import blogposts

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import blogposts_id

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import blogposts_id_attachments

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import blogposts_id_custom_content

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import blogposts_id_labels

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import blogposts_id_likes_count

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import blogposts_id_likes_users

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import blogposts_blogpost_id_properties

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import blogposts_blogpost_id_properties_property_id

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import blogposts_id_operations

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import blogposts_id_versions

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import blogposts_blogpost_id_versions_version_number

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import content_convert_ids_to_types

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import custom_content

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import custom_content_id

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import custom_content_id_attachments

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import custom_content_id_footer_comments

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import custom_content_id_labels

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import custom_content_id_operations

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import custom_content_custom_content_id_properties

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import custom_content_custom_content_id_properties_property_id

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import labels

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import labels_id_attachments

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import labels_id_blogposts

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import labels_id_pages'''

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import pages

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import pages_id

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import pages_id_attachments

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import pages_id_custom_content

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import pages_id_labels

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import pages_id_likes_count

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import pages_id_likes_users

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import pages_id_operations

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import pages_page_id_properties

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import pages_page_id_properties_property_id

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import pages_id_title

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import pages_id_versions

'''from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import whiteboards

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import whiteboards_id

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import whiteboards_id_properties

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import whiteboards_whiteboard_id_properties_property_id

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import whiteboards_id_operations

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import whiteboards_id_direct_children

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import whiteboards_id_descendants

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import whiteboards_id_ancestors

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import databases

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import databases_id

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import databases_id_properties

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import databases_database_id_properties_property_id

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import databases_id_operations

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import databases_id_direct_children

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import databases_id_descendants

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import databases_id_ancestors

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import embeds

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import embeds_id

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import embeds_id_properties

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import embeds_embed_id_properties_property_id

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import embeds_id_operations

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import embeds_id_direct_children

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import embeds_id_descendants

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import embeds_id_ancestors

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import folders

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import folders_id

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import folders_id_properties

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import folders_folder_id_properties_property_id

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import folders_id_operations

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import folders_id_direct_children

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import folders_id_descendants

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import folders_id_ancestors

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import pages_page_id_versions_version_number

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import custom_content_custom_content_id_versions

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import custom_content_custom_content_id_versions_version_number

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import spaces

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import spaces_id

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import spaces_id_blogposts

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import spaces_id_labels

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import spaces_id_content_labels

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import spaces_id_custom_content

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import spaces_id_operations

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import spaces_id_pages

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import spaces_space_id_properties

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import spaces_space_id_properties_property_id

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import spaces_id_permissions

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import space_permissions

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import space_roles

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import space_roles_id

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import spaces_id_role_assignments

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import pages_id_footer_comments

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import pages_id_inline_comments

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import blogposts_id_footer_comments

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import blogposts_id_inline_comments

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import footer_comments

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import footer_comments_comment_id

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import footer_comments_id_children

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import footer_comments_id_likes_count

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import footer_comments_id_likes_users

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import footer_comments_id_operations

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import footer_comments_id_versions

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import footer_comments_id_versions_version_number

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import inline_comments

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import inline_comments_comment_id

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import inline_comments_id_children

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import inline_comments_id_likes_count

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import inline_comments_id_likes_users

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import inline_comments_id_operations

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import inline_comments_id_versions

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import inline_comments_id_versions_version_number

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import comments_comment_id_properties

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import comments_comment_id_properties_property_id

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import tasks

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import tasks_id

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import pages_id_children

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import custom_content_id_children

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import pages_id_direct_children

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import pages_id_ancestors

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import pages_id_descendants

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import users_bulk

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import user_access_check_access_by_email

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import user_access_invite_by_email

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import data_policies_metadata

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import data_policies_spaces

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import classification_levels

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import spaces_id_classification_level_default

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import pages_id_classification_level

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import pages_id_classification_level_reset

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import blogposts_id_classification_level

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import blogposts_id_classification_level_reset

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import whiteboards_id_classification_level

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import whiteboards_id_classification_level_reset

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import databases_id_classification_level

from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.tools import databases_id_classification_level_reset'''


def main():
    # Load environment variables
    load_dotenv()

    # Configure logging
    logging.basicConfig(level=logging.DEBUG)

    # Get MCP configuration from environment variables
    MCP_MODE = os.getenv("MCP_MODE", "STDIO")

    # Get host and port for server
    MCP_HOST = os.getenv("MCP_HOST", "localhost")
    MCP_PORT = int(os.getenv("MCP_PORT", "8000"))

    logging.info(f"Starting MCP server in {MCP_MODE} mode on {MCP_HOST}:{MCP_PORT}")

    # Get agent name from environment variables
    AGENT_NAME = os.getenv("AGENT_NAME", "CONFLUENCE Agent")
    logging.info(f"Agent name: {AGENT_NAME}")

    # Create server instance
    if MCP_MODE == "SSE":
      mcp = FastMCP(f"{AGENT_NAME} MCP Server", host=MCP_HOST, port=MCP_PORT)
    else:
      mcp = FastMCP("CONFLUENCE MCP Server")


    '''# Register admin_key tools

    mcp.tool()(admin_key.get_admin_key)

    mcp.tool()(admin_key.enable_admin_key)

    mcp.tool()(admin_key.disable_admin_key)

    # Register attachments tools

    mcp.tool()(attachments.get_attachments)

    # Register attachments_id tools

    mcp.tool()(attachments_id.get_attachment_by_id)

    mcp.tool()(attachments_id.delete_attachment)

    # Register attachments_id_labels tools

    mcp.tool()(attachments_id_labels.get_attachment_labels)

    # Register attachments_id_operations tools

    mcp.tool()(attachments_id_operations.get_attachment_operations)

    # Register attachments_attachment_id_properties tools

    mcp.tool()(attachments_attachment_id_properties.get_attachment_content_properties)

    mcp.tool()(attachments_attachment_id_properties.create_attachment_property)

    # Register attachments_attachment_id_properties_property_id tools

    mcp.tool()(attachments_attachment_id_properties_property_id.get_attachment_content_properties_by_id)

    mcp.tool()(attachments_attachment_id_properties_property_id.update_attachment_property_by_id)

    mcp.tool()(attachments_attachment_id_properties_property_id.delete_attachment_property_by_id)

    # Register attachments_id_versions tools

    mcp.tool()(attachments_id_versions.get_attachment_versions)

    # Register attachments_attachment_id_versions_version_number tools

    mcp.tool()(attachments_attachment_id_versions_version_number.get_attachment_version_details)

    # Register attachments_id_footer_comments tools

    mcp.tool()(attachments_id_footer_comments.get_attachment_comments)

    # Register blogposts tools

    mcp.tool()(blogposts.get_blog_posts)

    mcp.tool()(blogposts.create_blog_post)

    # Register blogposts_id tools

    mcp.tool()(blogposts_id.get_blog_post_by_id)

    mcp.tool()(blogposts_id.update_blog_post)

    mcp.tool()(blogposts_id.delete_blog_post)

    # Register blogposts_id_attachments tools

    mcp.tool()(blogposts_id_attachments.get_blogpost_attachments)

    # Register blogposts_id_custom_content tools

    mcp.tool()(blogposts_id_custom_content.get_custom_content_by_type_in_blog_post)

    # Register blogposts_id_labels tools

    mcp.tool()(blogposts_id_labels.get_blog_post_labels)

    # Register blogposts_id_likes_count tools

    mcp.tool()(blogposts_id_likes_count.get_blog_post_like_count)

    # Register blogposts_id_likes_users tools

    mcp.tool()(blogposts_id_likes_users.get_blog_post_like_users)

    # Register blogposts_blogpost_id_properties tools

    mcp.tool()(blogposts_blogpost_id_properties.get_blogpost_content_properties)

    mcp.tool()(blogposts_blogpost_id_properties.create_blogpost_property)

    # Register blogposts_blogpost_id_properties_property_id tools

    mcp.tool()(blogposts_blogpost_id_properties_property_id.get_blogpost_content_properties_by_id)

    mcp.tool()(blogposts_blogpost_id_properties_property_id.update_blogpost_property_by_id)

    mcp.tool()(blogposts_blogpost_id_properties_property_id.delete_blogpost_property_by_id)

    # Register blogposts_id_operations tools

    mcp.tool()(blogposts_id_operations.get_blog_post_operations)

    # Register blogposts_id_versions tools

    mcp.tool()(blogposts_id_versions.get_blog_post_versions)

    # Register blogposts_blogpost_id_versions_version_number tools

    mcp.tool()(blogposts_blogpost_id_versions_version_number.get_blog_post_version_details)

    # Register content_convert_ids_to_types tools

    mcp.tool()(content_convert_ids_to_types.convert_content_ids_to_content_types)

    # Register custom_content tools

    mcp.tool()(custom_content.get_custom_content_by_type)

    mcp.tool()(custom_content.create_custom_content)

    # Register custom_content_id tools

    mcp.tool()(custom_content_id.get_custom_content_by_id)

    mcp.tool()(custom_content_id.update_custom_content)

    mcp.tool()(custom_content_id.delete_custom_content)

    # Register custom_content_id_attachments tools

    mcp.tool()(custom_content_id_attachments.get_custom_content_attachments)

    # Register custom_content_id_footer_comments tools

    mcp.tool()(custom_content_id_footer_comments.get_custom_content_comments)

    # Register custom_content_id_labels tools

    mcp.tool()(custom_content_id_labels.get_custom_content_labels)

    # Register custom_content_id_operations tools

    mcp.tool()(custom_content_id_operations.get_custom_content_operations)

    # Register custom_content_custom_content_id_properties tools

    mcp.tool()(custom_content_custom_content_id_properties.get_custom_content_content_properties)

    mcp.tool()(custom_content_custom_content_id_properties.create_custom_content_property)

    # Register custom_content_custom_content_id_properties_property_id tools

    mcp.tool()(custom_content_custom_content_id_properties_property_id.get_custom_content_content_properties_by_id)

    mcp.tool()(custom_content_custom_content_id_properties_property_id.update_custom_content_property_by_id)

    mcp.tool()(custom_content_custom_content_id_properties_property_id.delete_custom_content_property_by_id)

    # Register labels tools

    mcp.tool()(labels.get_labels)

    # Register labels_id_attachments tools

    mcp.tool()(labels_id_attachments.get_label_attachments)

    # Register labels_id_blogposts tools

    mcp.tool()(labels_id_blogposts.get_label_blog_posts)

    # Register labels_id_pages tools

    mcp.tool()(labels_id_pages.get_label_pages)'''

    # Register pages tools

    mcp.tool()(pages.get_pages)

    mcp.tool()(pages.create_page)

    # Register pages_id tools

    mcp.tool()(pages_id.get_page_by_id)

    mcp.tool()(pages_id.update_page)

    mcp.tool()(pages_id.delete_page)

    # Register pages_id_attachments tools

    mcp.tool()(pages_id_attachments.get_page_attachments)

    # Register pages_id_custom_content tools

    mcp.tool()(pages_id_custom_content.get_custom_content_by_type_in_page)

    # Register pages_id_labels tools

    mcp.tool()(pages_id_labels.get_page_labels)

    # Register pages_id_likes_count tools

    mcp.tool()(pages_id_likes_count.get_page_like_count)

    # Register pages_id_likes_users tools

    mcp.tool()(pages_id_likes_users.get_page_like_users)

    # Register pages_id_operations tools

    mcp.tool()(pages_id_operations.get_page_operations)

    # Register pages_page_id_properties tools

    mcp.tool()(pages_page_id_properties.get_page_content_properties)

    mcp.tool()(pages_page_id_properties.create_page_property)

    # Register pages_page_id_properties_property_id tools

    mcp.tool()(pages_page_id_properties_property_id.get_page_content_properties_by_id)

    mcp.tool()(pages_page_id_properties_property_id.update_page_property_by_id)

    mcp.tool()(pages_page_id_properties_property_id.delete_page_property_by_id)

    # Register pages_id_title tools

    mcp.tool()(pages_id_title.update_page_title)

    # Register pages_id_versions tools

    mcp.tool()(pages_id_versions.get_page_versions)

    '''# Register whiteboards tools

    mcp.tool()(whiteboards.create_whiteboard)

    # Register whiteboards_id tools

    mcp.tool()(whiteboards_id.get_whiteboard_by_id)

    mcp.tool()(whiteboards_id.delete_whiteboard)

    # Register whiteboards_id_properties tools

    mcp.tool()(whiteboards_id_properties.get_whiteboard_content_properties)

    mcp.tool()(whiteboards_id_properties.create_whiteboard_property)

    # Register whiteboards_whiteboard_id_properties_property_id tools

    mcp.tool()(whiteboards_whiteboard_id_properties_property_id.get_whiteboard_content_properties_by_id)

    mcp.tool()(whiteboards_whiteboard_id_properties_property_id.update_whiteboard_property_by_id)

    mcp.tool()(whiteboards_whiteboard_id_properties_property_id.delete_whiteboard_property_by_id)

    # Register whiteboards_id_operations tools

    mcp.tool()(whiteboards_id_operations.get_whiteboard_operations)

    # Register whiteboards_id_direct_children tools

    mcp.tool()(whiteboards_id_direct_children.get_whiteboard_direct_children)

    # Register whiteboards_id_descendants tools

    mcp.tool()(whiteboards_id_descendants.get_whiteboard_descendants)

    # Register whiteboards_id_ancestors tools

    mcp.tool()(whiteboards_id_ancestors.get_whiteboard_ancestors)

    # Register databases tools

    mcp.tool()(databases.create_database)

    # Register databases_id tools

    mcp.tool()(databases_id.get_database_by_id)

    mcp.tool()(databases_id.delete_database)

    # Register databases_id_properties tools

    mcp.tool()(databases_id_properties.get_database_content_properties)

    mcp.tool()(databases_id_properties.create_database_property)

    # Register databases_database_id_properties_property_id tools

    mcp.tool()(databases_database_id_properties_property_id.get_database_content_properties_by_id)

    mcp.tool()(databases_database_id_properties_property_id.update_database_property_by_id)

    mcp.tool()(databases_database_id_properties_property_id.delete_database_property_by_id)

    # Register databases_id_operations tools

    mcp.tool()(databases_id_operations.get_database_operations)

    # Register databases_id_direct_children tools

    mcp.tool()(databases_id_direct_children.get_database_direct_children)

    # Register databases_id_descendants tools

    mcp.tool()(databases_id_descendants.get_database_descendants)

    # Register databases_id_ancestors tools

    mcp.tool()(databases_id_ancestors.get_database_ancestors)

    # Register embeds tools

    mcp.tool()(embeds.create_smart_link)

    # Register embeds_id tools

    mcp.tool()(embeds_id.get_smart_link_by_id)

    mcp.tool()(embeds_id.delete_smart_link)

    # Register embeds_id_properties tools

    mcp.tool()(embeds_id_properties.get_smart_link_content_properties)

    mcp.tool()(embeds_id_properties.create_smart_link_property)

    # Register embeds_embed_id_properties_property_id tools

    mcp.tool()(embeds_embed_id_properties_property_id.get_smart_link_content_properties_by_id)

    mcp.tool()(embeds_embed_id_properties_property_id.update_smart_link_property_by_id)

    mcp.tool()(embeds_embed_id_properties_property_id.delete_smart_link_property_by_id)

    # Register embeds_id_operations tools

    mcp.tool()(embeds_id_operations.get_smart_link_operations)

    # Register embeds_id_direct_children tools

    mcp.tool()(embeds_id_direct_children.get_smart_link_direct_children)

    # Register embeds_id_descendants tools

    mcp.tool()(embeds_id_descendants.get_smart_link_descendants)

    # Register embeds_id_ancestors tools

    mcp.tool()(embeds_id_ancestors.get_smart_link_ancestors)

    # Register folders tools

    mcp.tool()(folders.create_folder)

    # Register folders_id tools

    mcp.tool()(folders_id.get_folder_by_id)

    mcp.tool()(folders_id.delete_folder)

    # Register folders_id_properties tools

    mcp.tool()(folders_id_properties.get_folder_content_properties)

    mcp.tool()(folders_id_properties.create_folder_property)

    # Register folders_folder_id_properties_property_id tools

    mcp.tool()(folders_folder_id_properties_property_id.get_folder_content_properties_by_id)

    mcp.tool()(folders_folder_id_properties_property_id.update_folder_property_by_id)

    mcp.tool()(folders_folder_id_properties_property_id.delete_folder_property_by_id)

    # Register folders_id_operations tools

    mcp.tool()(folders_id_operations.get_folder_operations)

    # Register folders_id_direct_children tools

    mcp.tool()(folders_id_direct_children.get_folder_direct_children)

    # Register folders_id_descendants tools

    mcp.tool()(folders_id_descendants.get_folder_descendants)

    # Register folders_id_ancestors tools

    mcp.tool()(folders_id_ancestors.get_folder_ancestors)

    # Register pages_page_id_versions_version_number tools

    mcp.tool()(pages_page_id_versions_version_number.get_page_version_details)

    # Register custom_content_custom_content_id_versions tools

    mcp.tool()(custom_content_custom_content_id_versions.get_custom_content_versions)

    # Register custom_content_custom_content_id_versions_version_number tools

    mcp.tool()(custom_content_custom_content_id_versions_version_number.get_custom_content_version_details)

    # Register spaces tools

    mcp.tool()(spaces.get_spaces)

    mcp.tool()(spaces.create_space)

    # Register spaces_id tools

    mcp.tool()(spaces_id.get_space_by_id)

    # Register spaces_id_blogposts tools

    mcp.tool()(spaces_id_blogposts.get_blog_posts_in_space)

    # Register spaces_id_labels tools

    mcp.tool()(spaces_id_labels.get_space_labels)

    # Register spaces_id_content_labels tools

    mcp.tool()(spaces_id_content_labels.get_space_content_labels)

    # Register spaces_id_custom_content tools

    mcp.tool()(spaces_id_custom_content.get_custom_content_by_type_in_space)

    # Register spaces_id_operations tools

    mcp.tool()(spaces_id_operations.get_space_operations)

    # Register spaces_id_pages tools

    mcp.tool()(spaces_id_pages.get_pages_in_space)

    # Register spaces_space_id_properties tools

    mcp.tool()(spaces_space_id_properties.get_space_properties)

    mcp.tool()(spaces_space_id_properties.create_space_property)

    # Register spaces_space_id_properties_property_id tools

    mcp.tool()(spaces_space_id_properties_property_id.get_space_property_by_id)

    mcp.tool()(spaces_space_id_properties_property_id.update_space_property_by_id)

    mcp.tool()(spaces_space_id_properties_property_id.delete_space_property_by_id)

    # Register spaces_id_permissions tools

    mcp.tool()(spaces_id_permissions.get_space_permissions_assignments)

    # Register space_permissions tools

    mcp.tool()(space_permissions.get_available_space_permissions)

    # Register space_roles tools

    mcp.tool()(space_roles.get_available_space_roles)

    # Register space_roles_id tools

    mcp.tool()(space_roles_id.get_space_roles_by_id)

    # Register spaces_id_role_assignments tools

    mcp.tool()(spaces_id_role_assignments.get_space_role_assignments)

    mcp.tool()(spaces_id_role_assignments.set_space_role_assignments)

    # Register pages_id_footer_comments tools

    mcp.tool()(pages_id_footer_comments.get_page_footer_comments)

    # Register pages_id_inline_comments tools

    mcp.tool()(pages_id_inline_comments.get_page_inline_comments)

    # Register blogposts_id_footer_comments tools

    mcp.tool()(blogposts_id_footer_comments.get_blog_post_footer_comments)

    # Register blogposts_id_inline_comments tools

    mcp.tool()(blogposts_id_inline_comments.get_blog_post_inline_comments)

    # Register footer_comments tools

    mcp.tool()(footer_comments.get_footer_comments)

    mcp.tool()(footer_comments.create_footer_comment)

    # Register footer_comments_comment_id tools

    mcp.tool()(footer_comments_comment_id.get_footer_comment_by_id)

    mcp.tool()(footer_comments_comment_id.update_footer_comment)

    mcp.tool()(footer_comments_comment_id.delete_footer_comment)

    # Register footer_comments_id_children tools

    mcp.tool()(footer_comments_id_children.get_footer_comment_children)

    # Register footer_comments_id_likes_count tools

    mcp.tool()(footer_comments_id_likes_count.get_footer_like_count)

    # Register footer_comments_id_likes_users tools

    mcp.tool()(footer_comments_id_likes_users.get_footer_like_users)

    # Register footer_comments_id_operations tools

    mcp.tool()(footer_comments_id_operations.get_footer_comment_operations)

    # Register footer_comments_id_versions tools

    mcp.tool()(footer_comments_id_versions.get_footer_comment_versions)

    # Register footer_comments_id_versions_version_number tools

    mcp.tool()(footer_comments_id_versions_version_number.get_footer_comment_version_details)

    # Register inline_comments tools

    mcp.tool()(inline_comments.get_inline_comments)

    mcp.tool()(inline_comments.create_inline_comment)

    # Register inline_comments_comment_id tools

    mcp.tool()(inline_comments_comment_id.get_inline_comment_by_id)

    mcp.tool()(inline_comments_comment_id.update_inline_comment)

    mcp.tool()(inline_comments_comment_id.delete_inline_comment)

    # Register inline_comments_id_children tools

    mcp.tool()(inline_comments_id_children.get_inline_comment_children)

    # Register inline_comments_id_likes_count tools

    mcp.tool()(inline_comments_id_likes_count.get_inline_like_count)

    # Register inline_comments_id_likes_users tools

    mcp.tool()(inline_comments_id_likes_users.get_inline_like_users)

    # Register inline_comments_id_operations tools

    mcp.tool()(inline_comments_id_operations.get_inline_comment_operations)

    # Register inline_comments_id_versions tools

    mcp.tool()(inline_comments_id_versions.get_inline_comment_versions)

    # Register inline_comments_id_versions_version_number tools

    mcp.tool()(inline_comments_id_versions_version_number.get_inline_comment_version_details)

    # Register comments_comment_id_properties tools

    mcp.tool()(comments_comment_id_properties.get_comment_content_properties)

    mcp.tool()(comments_comment_id_properties.create_comment_property)

    # Register comments_comment_id_properties_property_id tools

    mcp.tool()(comments_comment_id_properties_property_id.get_comment_content_properties_by_id)

    mcp.tool()(comments_comment_id_properties_property_id.update_comment_property_by_id)

    mcp.tool()(comments_comment_id_properties_property_id.delete_comment_property_by_id)

    # Register tasks tools

    mcp.tool()(tasks.get_tasks)

    # Register tasks_id tools

    mcp.tool()(tasks_id.get_task_by_id)

    mcp.tool()(tasks_id.update_task)

    # Register pages_id_children tools

    mcp.tool()(pages_id_children.get_child_pages)

    # Register custom_content_id_children tools

    mcp.tool()(custom_content_id_children.get_child_custom_content)

    # Register pages_id_direct_children tools

    mcp.tool()(pages_id_direct_children.get_page_direct_children)

    # Register pages_id_ancestors tools

    mcp.tool()(pages_id_ancestors.get_page_ancestors)

    # Register pages_id_descendants tools

    mcp.tool()(pages_id_descendants.get_page_descendants)

    # Register users_bulk tools

    mcp.tool()(users_bulk.create_bulk_user_lookup)

    # Register user_access_check_access_by_email tools

    mcp.tool()(user_access_check_access_by_email.check_access_by_email)

    # Register user_access_invite_by_email tools

    mcp.tool()(user_access_invite_by_email.invite_by_email)

    # Register data_policies_metadata tools

    mcp.tool()(data_policies_metadata.get_data_policy_metadata)

    # Register data_policies_spaces tools

    mcp.tool()(data_policies_spaces.get_data_policy_spaces)

    # Register classification_levels tools

    mcp.tool()(classification_levels.get_classification_levels)

    # Register spaces_id_classification_level_default tools

    mcp.tool()(spaces_id_classification_level_default.get_space_default_classification_level)

    mcp.tool()(spaces_id_classification_level_default.put_space_default_classification_level)

    mcp.tool()(spaces_id_classification_level_default.delete_space_default_classification_level)

    # Register pages_id_classification_level tools

    mcp.tool()(pages_id_classification_level.get_page_classification_level)

    mcp.tool()(pages_id_classification_level.put_page_classification_level)

    # Register pages_id_classification_level_reset tools

    mcp.tool()(pages_id_classification_level_reset.post_page_classification_level)

    # Register blogposts_id_classification_level tools

    mcp.tool()(blogposts_id_classification_level.get_blog_post_classification_level)

    mcp.tool()(blogposts_id_classification_level.put_blog_post_classification_level)

    # Register blogposts_id_classification_level_reset tools

    mcp.tool()(blogposts_id_classification_level_reset.post_blog_post_classification_level)

    # Register whiteboards_id_classification_level tools

    mcp.tool()(whiteboards_id_classification_level.get_whiteboard_classification_level)

    mcp.tool()(whiteboards_id_classification_level.put_whiteboard_classification_level)

    # Register whiteboards_id_classification_level_reset tools

    mcp.tool()(whiteboards_id_classification_level_reset.post_whiteboard_classification_level)

    # Register databases_id_classification_level tools

    mcp.tool()(databases_id_classification_level.get_database_classification_level)

    mcp.tool()(databases_id_classification_level.put_database_classification_level)

    # Register databases_id_classification_level_reset tools

    mcp.tool()(databases_id_classification_level_reset.post_database_classification_level)'''


    # Run the MCP server
    mcp.run()

if __name__ == "__main__":
    main()