# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /api/version operations"""


async def get_version() -> str:
    '''
    Returns version information for testing.

    Returns:
        str: A simple version string for testing.
    '''
    return "Version 0.1.0"