# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /user/{username} operations"""

import logging
from typing import Dict, Any
from agent_petstore.protocol_bindings.mcp_server.mcp_petstore.api.client import make_api_request, assemble_nested_body

# Configure logging
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger("mcp_tools")


async def get_user_by_name(path_username: str) -> Dict[str, Any]:
    '''
    Retrieve user details by username.

    Args:
        path_username (str): The username to fetch details for. Use 'user1' for testing.

    Returns:
        Dict[str, Any]: The JSON response containing user details.

    Raises:
        Exception: If the API request fails or returns an error.

    OpenAPI Specification:
        get:
          summary: Get user by user name
          description: Retrieve user details based on the provided username.
          operationId: getUserByName
          parameters:
            - name: username
              in: path
              required: true
              description: The name that needs to be fetched. Use 'user1' for testing.
              schema:
                type: string
          responses:
            '200':
              description: Successful response with user details.
              content:
                application/json:
                  schema:
                    type: object
            '404':
              description: User not found.
              content:
                application/json:
                  schema:
                    type: object
            '500':
              description: Server error.
              content:
                application/json:
                  schema:
                    type: object
    '''
    logger.debug("Making GET request to /user/{username}")

    params = {}
    data = {}

    flat_body = {}
    data = assemble_nested_body(flat_body)

    success, response = await make_api_request(f"/user/{path_username}", method="GET", params=params, data=data)

    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get("error", "Request failed")}
    return response


async def update_user(
    path_username: str,
    body_id: int = None,
    body_username: str = None,
    body_firstName: str = None,
    body_lastName: str = None,
    body_email: str = None,
    body_password: str = None,
    body_phone: str = None,
    body_userStatus: int = None,
) -> Dict[str, Any]:
    '''
    Update an existing user resource.

    Args:
        path_username (str): The username of the user to update.
        body_id (int, optional): The unique identifier of the user. Defaults to None.
        body_username (str, optional): The new username for the user. Defaults to None.
        body_firstName (str, optional): The new first name of the user. Defaults to None.
        body_lastName (str, optional): The new last name of the user. Defaults to None.
        body_email (str, optional): The new email address of the user. Defaults to None.
        body_password (str, optional): The new password for the user. Defaults to None.
        body_phone (str, optional): The new phone number of the user. Defaults to None.
        body_userStatus (int, optional): The new status code for the user. Defaults to None.

    Returns:
        Dict[str, Any]: The JSON response from the API call, containing the updated user information or an error message.

    Raises:
        Exception: If the API request fails or returns an error.

    OpenAPI Specification:
        put:
          summary: Update an existing user
          description: This can only be done by the logged in user.
          operationId: updateUser
          tags:
            - user
          parameters:
            - name: username
              in: path
              required: true
              description: The name of the user to update.
              schema:
                type: string
          requestBody:
            required: true
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    id:
                      type: integer
                      format: int64
                      description: The unique identifier of the user.
                    username:
                      type: string
                      description: The new username for the user.
                    firstName:
                      type: string
                      description: The new first name of the user.
                    lastName:
                      type: string
                      description: The new last name of the user.
                    email:
                      type: string
                      description: The new email address of the user.
                    password:
                      type: string
                      description: The new password for the user.
                    phone:
                      type: string
                      description: The new phone number of the user.
                    userStatus:
                      type: integer
                      format: int32
                      description: The new status code for the user.
          responses:
            '200':
              description: User updated successfully.
              content:
                application/json:
                  schema:
                    type: object
            '400':
              description: Invalid user supplied.
            '404':
              description: User not found.
    '''
    logger.debug("Making PUT request to /user/{username}")

    params = {}
    data = {}

    flat_body = {}
    if body_id is not None:
        flat_body["id"] = body_id
    if body_username is not None:
        flat_body["username"] = body_username
    if body_firstName is not None:
        flat_body["firstName"] = body_firstName
    if body_lastName is not None:
        flat_body["lastName"] = body_lastName
    if body_email is not None:
        flat_body["email"] = body_email
    if body_password is not None:
        flat_body["password"] = body_password
    if body_phone is not None:
        flat_body["phone"] = body_phone
    if body_userStatus is not None:
        flat_body["userStatus"] = body_userStatus
    data = assemble_nested_body(flat_body)

    success, response = await make_api_request(f"/user/{path_username}", method="PUT", params=params, data=data)

    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get("error", "Request failed")}
    return response


async def delete_user(path_username: str) -> Dict[str, Any]:
    '''
    Deletes a user resource by username.

    Args:
        path_username (str): The username of the user to be deleted.

    Returns:
        Dict[str, Any]: The JSON response from the API call.

    Raises:
        Exception: If the API request fails or returns an error.

    OpenAPI Specification:
      delete:
        summary: Delete user resource
        description: This can only be done by the logged in user.
        operationId: deleteUser
        tags:
          - user
        parameters:
          - name: username
            in: path
            description: The name that needs to be deleted
            required: true
            schema:
              type: string
        responses:
          '200':
            description: User deleted successfully
            content:
              application/json:
                schema:
                  type: object
          '400':
            description: Invalid username supplied
            content:
              application/json:
                schema:
                  type: object
          '404':
            description: User not found
            content:
              application/json:
                schema:
                  type: object
          '401':
            description: Unauthorized
            content:
              application/json:
                schema:
                  type: object
    '''
    logger.debug("Making DELETE request to /user/{username}")

    params = {}
    data = {}

    flat_body = {}
    data = assemble_nested_body(flat_body)

    success, response = await make_api_request(f"/user/{path_username}", method="DELETE", params=params, data=data)

    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get("error", "Request failed")}
    return response