
# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Childrencommentmodel"""

from typing import Dict, List, Optional
from datetime import datetime
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Childrencommentmodel(BaseModel):
    """Childrencommentmodel model"""



class ChildrencommentmodelResponse(APIResponse):
    """Response model for Childrencommentmodel"""
    data: Optional[Childrencommentmodel] = None


class ChildrencommentmodelListResponse(APIResponse):
    """List response model for Childrencommentmodel"""
    data: List[Childrencommentmodel] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None