
# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Childcustomcontent"""

from typing import Dict, List, Optional
from datetime import datetime
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Childcustomcontent(BaseModel):
    """Childcustomcontent model"""



class ChildcustomcontentResponse(APIResponse):
    """Response model for Childcustomcontent"""
    data: Optional[Childcustomcontent] = None


class ChildcustomcontentListResponse(APIResponse):
    """List response model for Childcustomcontent"""
    data: List[Childcustomcontent] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None