
# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Createinlinecommentmodel"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Createinlinecommentmodel(BaseModel):
    """Createinlinecommentmodel model"""



class CreateinlinecommentmodelResponse(APIResponse):
    """Response model for Createinlinecommentmodel"""
    data: Optional[Createinlinecommentmodel] = None


class CreateinlinecommentmodelListResponse(APIResponse):
    """List response model for Createinlinecommentmodel"""
    data: List[Createinlinecommentmodel] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None