
# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Customcontentsingle"""

from typing import Dict, List, Optional
from datetime import datetime
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Customcontentsingle(BaseModel):
    """Customcontentsingle model"""



class CustomcontentsingleResponse(APIResponse):
    """Response model for Customcontentsingle"""
    data: Optional[Customcontentsingle] = None


class CustomcontentsingleListResponse(APIResponse):
    """List response model for Customcontentsingle"""
    data: List[Customcontentsingle] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None