
# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Customcontentcommentmodel"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Customcontentcommentmodel(BaseModel):
    """Customcontentcommentmodel model"""



class CustomcontentcommentmodelResponse(APIResponse):
    """Response model for Customcontentcommentmodel"""
    data: Optional[Customcontentcommentmodel] = None


class CustomcontentcommentmodelListResponse(APIResponse):
    """List response model for Customcontentcommentmodel"""
    data: List[Customcontentcommentmodel] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None