
# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Multientitylinks"""

from typing import Dict, List, Optional
from datetime import datetime
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Multientitylinks(BaseModel):
    """Multientitylinks model"""



class MultientitylinksResponse(APIResponse):
    """Response model for Multientitylinks"""
    data: Optional[Multientitylinks] = None


class MultientitylinksListResponse(APIResponse):
    """List response model for Multientitylinks"""
    data: List[Multientitylinks] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None