
# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Operation"""

from typing import Dict, List, Optional
from datetime import datetime
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Operation(BaseModel):
    """Operation model"""



class OperationResponse(APIResponse):
    """Response model for Operation"""
    data: Optional[Operation] = None


class OperationListResponse(APIResponse):
    """List response model for Operation"""
    data: List[Operation] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None