
# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Pageinlinecommentmodel"""

from typing import Dict, List, Optional
from datetime import datetime
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Pageinlinecommentmodel(BaseModel):
    """Pageinlinecommentmodel model"""



class PageinlinecommentmodelResponse(APIResponse):
    """Response model for Pageinlinecommentmodel"""
    data: Optional[Pageinlinecommentmodel] = None


class PageinlinecommentmodelListResponse(APIResponse):
    """List response model for Pageinlinecommentmodel"""
    data: List[Pageinlinecommentmodel] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None