
# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Pageversion"""

from typing import Dict, List, Optional
from datetime import datetime
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Pageversion(BaseModel):
    """Pageversion model"""



class PageversionResponse(APIResponse):
    """Response model for Pageversion"""
    data: Optional[Pageversion] = None


class PageversionListResponse(APIResponse):
    """List response model for Pageversion"""
    data: List[Pageversion] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None