
# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Spacedescriptionbodyrepresentation"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Spacedescriptionbodyrepresentation(BaseModel):
    """The formats a space description can be represented as. A subset of BodyRepresentation."""



class SpacedescriptionbodyrepresentationResponse(APIResponse):
    """Response model for Spacedescriptionbodyrepresentation"""
    data: Optional[Spacedescriptionbodyrepresentation] = None


class SpacedescriptionbodyrepresentationListResponse(APIResponse):
    """List response model for Spacedescriptionbodyrepresentation"""
    data: List[Spacedescriptionbodyrepresentation] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None