
# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Task"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Task(BaseModel):
    """Task model"""



class TaskResponse(APIResponse):
    """Response model for Task"""
    data: Optional[Task] = None


class TaskListResponse(APIResponse):
    """List response model for Task"""
    data: List[Task] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None