
# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Abstractpagelinks"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Abstractpagelinks(BaseModel):
    """Abstractpagelinks model"""



class AbstractpagelinksResponse(APIResponse):
    """Response model for Abstractpagelinks"""
    data: Optional[Abstractpagelinks] = None


class AbstractpagelinksListResponse(APIResponse):
    """List response model for Abstractpagelinks"""
    data: List[Abstractpagelinks] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None