
# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Ancestor"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Ancestor(BaseModel):
    """Ancestor model"""



class AncestorResponse(APIResponse):
    """Response model for Ancestor"""
    data: Optional[Ancestor] = None


class AncestorListResponse(APIResponse):
    """List response model for Ancestor"""
    data: List[Ancestor] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None