
# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Childrenresponse"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Childrenresponse(BaseModel):
    """Childrenresponse model"""



class ChildrenresponseResponse(APIResponse):
    """Response model for Childrenresponse"""
    data: Optional[Childrenresponse] = None


class ChildrenresponseListResponse(APIResponse):
    """List response model for Childrenresponse"""
    data: List[Childrenresponse] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None