
# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Commentlinks"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Commentlinks(BaseModel):
    """Commentlinks model"""



class CommentlinksResponse(APIResponse):
    """Response model for Commentlinks"""
    data: Optional[Commentlinks] = None


class CommentlinksListResponse(APIResponse):
    """List response model for Commentlinks"""
    data: List[Commentlinks] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None