
# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Customcontentbodyrepresentationsingle"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Customcontentbodyrepresentationsingle(BaseModel):
    """The formats a custom content body can be represented as. A subset of BodyRepresentation."""



class CustomcontentbodyrepresentationsingleResponse(APIResponse):
    """Response model for Customcontentbodyrepresentationsingle"""
    data: Optional[Customcontentbodyrepresentationsingle] = None


class CustomcontentbodyrepresentationsingleListResponse(APIResponse):
    """List response model for Customcontentbodyrepresentationsingle"""
    data: List[Customcontentbodyrepresentationsingle] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None