
# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Foldersingle"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Foldersingle(BaseModel):
    """Foldersingle model"""



class FoldersingleResponse(APIResponse):
    """Response model for Foldersingle"""
    data: Optional[Foldersingle] = None


class FoldersingleListResponse(APIResponse):
    """List response model for Foldersingle"""
    data: List[Foldersingle] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None