
# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Folderlinks"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Folderlinks(BaseModel):
    """Folderlinks model"""



class FolderlinksResponse(APIResponse):
    """Response model for Folderlinks"""
    data: Optional[Folderlinks] = None


class FolderlinksListResponse(APIResponse):
    """List response model for Folderlinks"""
    data: List[Folderlinks] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None