
# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Labelsortorder"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Labelsortorder(BaseModel):
    """The sort fields for labels. The default sort direction is ascending. To sort in descending order, append a `-` character before the sort field. For example, `fieldName` or `-fieldName`."""



class LabelsortorderResponse(APIResponse):
    """Response model for Labelsortorder"""
    data: Optional[Labelsortorder] = None


class LabelsortorderListResponse(APIResponse):
    """List response model for Labelsortorder"""
    data: List[Labelsortorder] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None