
# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Like"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Like(BaseModel):
    """Like model"""



class LikeResponse(APIResponse):
    """Response model for Like"""
    data: Optional[Like] = None


class LikeListResponse(APIResponse):
    """List response model for Like"""
    data: List[Like] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None