
# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Pagebodywrite"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Pagebodywrite(BaseModel):
    """Pagebodywrite model"""



class PagebodywriteResponse(APIResponse):
    """Response model for Pagebodywrite"""
    data: Optional[Pagebodywrite] = None


class PagebodywriteListResponse(APIResponse):
    """List response model for Pagebodywrite"""
    data: List[Pagebodywrite] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None