
# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Spaceicon"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Spaceicon(BaseModel):
    """The icon of the space"""



class SpaceiconResponse(APIResponse):
    """Response model for Spaceicon"""
    data: Optional[Spaceicon] = None


class SpaceiconListResponse(APIResponse):
    """List response model for Spaceicon"""
    data: List[Spaceicon] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None