
# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Spacestatus"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Spacestatus(BaseModel):
    """The status of the space."""



class SpacestatusResponse(APIResponse):
    """Response model for Spacestatus"""
    data: Optional[Spacestatus] = None


class SpacestatusListResponse(APIResponse):
    """List response model for Spacestatus"""
    data: List[Spacestatus] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None