
# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Updateinlinecommentmodel"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Updateinlinecommentmodel(BaseModel):
    """Updateinlinecommentmodel model"""



class UpdateinlinecommentmodelResponse(APIResponse):
    """Response model for Updateinlinecommentmodel"""
    data: Optional[Updateinlinecommentmodel] = None


class UpdateinlinecommentmodelListResponse(APIResponse):
    """List response model for Updateinlinecommentmodel"""
    data: List[Updateinlinecommentmodel] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None