# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Entitymeta"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Entitymeta(BaseModel):
    """Metadata fields common to all versions/kinds of entity."""


class EntitymetaResponse(APIResponse):
    """Response model for Entitymeta"""

    data: Optional[Entitymeta] = None


class EntitymetaListResponse(APIResponse):
    """List response model for Entitymeta"""

    data: List[Entitymeta] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None
