
# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /pages/{id}/versions operations"""

import logging
from typing import Dict, Any, Optional, List
from pydantic import BaseModel
from agent_confluence.protocol_bindings.mcp_server.mcp_confluence.api.client import make_api_request

# Configure logging
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger("mcp_tools")


async def get_page_versions(path_id: int, param_body_format: str = None, param_cursor: str = None, param_limit: int = None, param_sort: str = None) -> Dict[str, Any]:
    """
    Get page versions

    OpenAPI Description:
        Returns the versions of specific page.

**[Permissions](https://confluence.atlassian.com/x/_AozKw) required**:
Permission to view the page and its corresponding space.

    Args:
    
        path_id (int): The ID of the page to be queried for its versions. If you don't know the page ID, use Get pages and filter the results.
    
        param_body_format (str): The content format types to be returned in the `body` field of the response. If available, the representation will be available under a response field of the same name under the `body` field.
    
        param_cursor (str): Used for pagination, this opaque cursor will be returned in the `next` URL in the `Link` response header. Use the relative URL in the `Link` header to retrieve the `next` set of results.
    
        param_limit (int): Maximum number of versions per result to return. If more results exist, use the `Link` header to retrieve a relative URL that will return the next set of results.
    
        param_sort (str): Used to sort the result by a particular field.
    

    Returns:
        Dict[str, Any]: The JSON response from the API call.

    Raises:
        Exception: If the API request fails or returns an error.
    """
    logger.debug("Making GET request to /pages/{id}/versions")

    params = {}
    data = {}
       
    params["body-format"] = param_body_format   
    params["cursor"] = param_cursor   
    params["limit"] = param_limit   
    params["sort"] = param_sort  

              

    success, response = await make_api_request(
        f"/pages/{path_id}/versions",
        method="GET",
        params=params,
        data=data
    )

    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get('error', 'Request failed')}
    return response
