# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Anomalystate"""


from pydantic import BaseModel, Field

from .base import APIResponse, PaginationInfo


class Anomalystate(BaseModel):
    """Describes the current state of an event or incident. Set by system."""


class AnomalystateResponse(APIResponse):
    """Response model for Anomalystate"""

    data: Anomalystate | None = None


class AnomalystateListResponse(APIResponse):
    """List response model for Anomalystate"""

    data: list[Anomalystate] = Field(default_factory=list)
    pagination: PaginationInfo | None = None
