# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Apitestsetupname"""


from pydantic import BaseModel, Field

from .base import APIResponse, PaginationInfo


class Apitestsetupname(BaseModel):
    """Name of your test setup step"""


class ApitestsetupnameResponse(APIResponse):
    """Response model for Apitestsetupname"""

    data: Apitestsetupname | None = None


class ApitestsetupnameListResponse(APIResponse):
    """List response model for Apitestsetupname"""

    data: list[Apitestsetupname] = Field(default_factory=list)
    pagination: PaginationInfo | None = None
