# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Apitestvalidationextract"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Apitestvalidationextract(BaseModel):
    """Validation step to extract values from custom data, response body, or
    existing variable
    """


class ApitestvalidationextractResponse(APIResponse):
    """Response model for Apitestvalidationextract"""

    data: Optional[Apitestvalidationextract] = None


class ApitestvalidationextractListResponse(APIResponse):
    """List response model for Apitestvalidationextract"""

    data: List[Apitestvalidationextract] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None
