# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Apitestrequests"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Apitestrequests(BaseModel):
    """Apitestrequests model"""


class ApitestrequestsResponse(APIResponse):
    """Response model for Apitestrequests"""

    data: Optional[Apitestrequests] = None


class ApitestrequestsListResponse(APIResponse):
    """List response model for Apitestrequests"""

    data: List[Apitestrequests] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None
