# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Apitestsave"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Apitestsave(BaseModel):
    """Save a custom field or response body to a variable"""


class ApitestsaveResponse(APIResponse):
    """Response model for Apitestsave"""

    data: Optional[Apitestsave] = None


class ApitestsaveListResponse(APIResponse):
    """List response model for Apitestsave"""

    data: List[Apitestsave] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None
