# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Apitestvalidationassert"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Apitestvalidationassert(BaseModel):
    """Validation step to assert custom data, response code, or response body."""


class ApitestvalidationassertResponse(APIResponse):
    """Response model for Apitestvalidationassert"""

    data: Optional[Apitestvalidationassert] = None


class ApitestvalidationassertListResponse(APIResponse):
    """List response model for Apitestvalidationassert"""

    data: List[Apitestvalidationassert] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None
