# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Apitestsource"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Apitestsource(BaseModel):
    """Source document to extract fields from"""


class ApitestsourceResponse(APIResponse):
    """Response model for Apitestsource"""

    data: Optional[Apitestsource] = None


class ApitestsourceListResponse(APIResponse):
    """List response model for Apitestsource"""

    data: List[Apitestsource] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None
