# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Apitestextractor"""


from pydantic import BaseModel, Field

from .base import APIResponse, PaginationInfo


class Apitestextractor(BaseModel):
    """Extracting language. This must be in JSONPath, XMLPath, or HTMLPath"""


class ApitestextractorResponse(APIResponse):
    """Response model for Apitestextractor"""

    data: Apitestextractor | None = None


class ApitestextractorListResponse(APIResponse):
    """List response model for Apitestextractor"""

    data: list[Apitestextractor] = Field(default_factory=list)
    pagination: PaginationInfo | None = None
