# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Basevalidateapiresponse"""


from pydantic import BaseModel, Field

from .base import APIResponse, PaginationInfo


class Basevalidateapiresponse(BaseModel):
    """Basevalidateapiresponse model"""


class BasevalidateapiresponseResponse(APIResponse):
    """Response model for Basevalidateapiresponse"""

    data: Basevalidateapiresponse | None = None


class BasevalidateapiresponseListResponse(APIResponse):
    """List response model for Basevalidateapiresponse"""

    data: list[Basevalidateapiresponse] = Field(default_factory=list)
    pagination: PaginationInfo | None = None
