# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Base models for the API"""


from pydantic import BaseModel


class APIResponse(BaseModel):
    """Base model for API responses"""

    success: bool
    data: dict | None = None
    error: str | None = None


class PaginationInfo(BaseModel):
    """Pagination information"""

    offset: int
    limit: int
    total: int | None = None
    more: bool | None = None
