# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Bigpandanotification"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Bigpandanotification(BaseModel):
    """Properties that link a notification to a BigPanda integration"""


class BigpandanotificationResponse(APIResponse):
    """Response model for Bigpandanotification"""

    data: Optional[Bigpandanotification] = None


class BigpandanotificationListResponse(APIResponse):
    """List response model for Bigpandanotification"""

    data: List[Bigpandanotification] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None
