# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Count"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Count(BaseModel):
    """Number of detectors that matched the query criteria"""


class CountResponse(APIResponse):
    """Response model for Count"""

    data: Optional[Count] = None


class CountListResponse(APIResponse):
    """List response model for Count"""

    data: List[Count] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None
