# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Customproperties"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Customproperties(BaseModel):
    """An array of custom properties for the test."""


class CustompropertiesResponse(APIResponse):
    """Response model for Customproperties"""

    data: Optional[Customproperties] = None


class CustompropertiesListResponse(APIResponse):
    """List response model for Customproperties"""

    data: List[Customproperties] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None
