# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Detectorevent"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Detectorevent(BaseModel):
    """Properties of a single event"""


class DetectoreventResponse(APIResponse):
    """Response model for Detectorevent"""

    data: Optional[Detectorevent] = None


class DetectoreventListResponse(APIResponse):
    """List response model for Detectorevent"""

    data: List[Detectorevent] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None
