# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Device"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Device(BaseModel):
    """Device model"""


class DeviceResponse(APIResponse):
    """Response model for Device"""

    data: Optional[Device] = None


class DeviceListResponse(APIResponse):
    """List response model for Device"""

    data: List[Device] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None
