# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Dimensions"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Dimensions(BaseModel):
    """Matched dimension names and values for the detector rule that triggered
    the event
    """


class DimensionsResponse(APIResponse):
    """Response model for Dimensions"""

    data: Optional[Dimensions] = None


class DimensionsListResponse(APIResponse):
    """List response model for Dimensions"""

    data: List[Dimensions] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None
