# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Dimensionmetadata"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Dimensionmetadata(BaseModel):
    """Metadata for a single dimension"""


class DimensionmetadataResponse(APIResponse):
    """Response model for Dimensionmetadata"""

    data: Optional[Dimensionmetadata] = None


class DimensionmetadataListResponse(APIResponse):
    """List response model for Dimensionmetadata"""

    data: List[Dimensionmetadata] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None
