# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Dimensionupdateresponse"""


from pydantic import BaseModel, Field

from .base import APIResponse, PaginationInfo


class Dimensionupdateresponse(BaseModel):
    """Dimension update response body"""


class DimensionupdateresponseResponse(APIResponse):
    """Response model for Dimensionupdateresponse"""

    data: Dimensionupdateresponse | None = None


class DimensionupdateresponseListResponse(APIResponse):
    """List response model for Dimensionupdateresponse"""

    data: list[Dimensionupdateresponse] = Field(default_factory=list)
    pagination: PaginationInfo | None = None
