# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Disabled"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Disabled(BaseModel):
    """Indicates that the alert rule is enabled or disabled"""


class DisabledResponse(APIResponse):
    """Response model for Disabled"""

    data: Optional[Disabled] = None


class DisabledListResponse(APIResponse):
    """List response model for Disabled"""

    data: List[Disabled] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None
