# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Displayname"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Displayname(BaseModel):
    """Data Table column header for publish block in the detector's chart"""


class DisplaynameResponse(APIResponse):
    """Response model for Displayname"""

    data: Optional[Displayname] = None


class DisplaynameListResponse(APIResponse):
    """List response model for Displayname"""

    data: List[Displayname] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None
