# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Emailnotification"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Emailnotification(BaseModel):
    """Properties that link a notification to an email address"""


class EmailnotificationResponse(APIResponse):
    """Response model for Emailnotification"""

    data: Optional[Emailnotification] = None


class EmailnotificationListResponse(APIResponse):
    """List response model for Emailnotification"""

    data: List[Emailnotification] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None
