# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Fragment"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Fragment(BaseModel):
    """Fragment of SignalFlow code containing a value that triggered an event"""


class FragmentResponse(APIResponse):
    """Response model for Fragment"""

    data: Optional[Fragment] = None


class FragmentListResponse(APIResponse):
    """List response model for Fragment"""

    data: List[Fragment] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None
