# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Getdetectorincidentsresponse"""


from pydantic import BaseModel, Field

from .base import APIResponse, PaginationInfo


class Getdetectorincidentsresponse(BaseModel):
    """List of incidents returned by the Retrieve Incidents query endpoint"""


class GetdetectorincidentsresponseResponse(APIResponse):
    """Response model for Getdetectorincidentsresponse"""

    data: Getdetectorincidentsresponse | None = None


class GetdetectorincidentsresponseListResponse(APIResponse):
    """List response model for Getdetectorincidentsresponse"""

    data: list[Getdetectorincidentsresponse] = Field(default_factory=list)
    pagination: PaginationInfo | None = None
