# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Gettestsresponse"""


from pydantic import BaseModel, Field

from .base import APIResponse, PaginationInfo


class Gettestsresponse(BaseModel):
    """Returns a list of all tests."""


class GettestsresponseResponse(APIResponse):
    """Response model for Gettestsresponse"""

    data: Gettestsresponse | None = None


class GettestsresponseListResponse(APIResponse):
    """List response model for Gettestsresponse"""

    data: list[Gettestsresponse] = Field(default_factory=list)
    pagination: PaginationInfo | None = None
