# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Getdetectorresponse"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Getdetectorresponse(BaseModel):
    """Properties of an individual detector"""


class GetdetectorresponseResponse(APIResponse):
    """Response model for Getdetectorresponse"""

    data: Optional[Getdetectorresponse] = None


class GetdetectorresponseListResponse(APIResponse):
    """List response model for Getdetectorresponse"""

    data: List[Getdetectorresponse] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None
