# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Getdetectoreventsresponse"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Getdetectoreventsresponse(BaseModel):
    """List of event objects"""


class GetdetectoreventsresponseResponse(APIResponse):
    """Response model for Getdetectoreventsresponse"""

    data: Optional[Getdetectoreventsresponse] = None


class GetdetectoreventsresponseListResponse(APIResponse):
    """List response model for Getdetectoreventsresponse"""

    data: List[Getdetectoreventsresponse] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None
