# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Incidenteventsource"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Incidenteventsource(BaseModel):
    """Individual stream or variable that matched a detector rule"""


class IncidenteventsourceResponse(APIResponse):
    """Response model for Incidenteventsource"""

    data: Optional[Incidenteventsource] = None


class IncidenteventsourceListResponse(APIResponse):
    """List response model for Incidenteventsource"""

    data: List[Incidenteventsource] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None
