# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Jiranotification"""


from pydantic import BaseModel, Field

from .base import APIResponse, PaginationInfo


class Jiranotification(BaseModel):
    """Properties that link a notification to a Jira integration"""


class JiranotificationResponse(APIResponse):
    """Response model for Jiranotification"""

    data: Jiranotification | None = None


class JiranotificationListResponse(APIResponse):
    """List response model for Jiranotification"""

    data: list[Jiranotification] = Field(default_factory=list)
    pagination: PaginationInfo | None = None
