# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Labelresolutions"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Labelresolutions(BaseModel):
    """Properties that control how often Splunk Observability Cloud checks for alert conditions"""


class LabelresolutionsResponse(APIResponse):
    """Response model for Labelresolutions"""

    data: Optional[Labelresolutions] = None


class LabelresolutionsListResponse(APIResponse):
    """List response model for Labelresolutions"""

    data: List[Labelresolutions] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None
