# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Maxdelay"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Maxdelay(BaseModel):
    """Upper limit of how long the SignalFlow computation waits for delayed data before continuing, in milliseconds. The default is 0, which tells SignalFlow to set the limit dynamically."""


class MaxdelayResponse(APIResponse):
    """Response model for Maxdelay"""

    data: Optional[Maxdelay] = None


class MaxdelayListResponse(APIResponse):
    """List response model for Maxdelay"""

    data: List[Maxdelay] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None
