# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Metricsmetadata"""


from pydantic import BaseModel, Field

from .base import APIResponse, PaginationInfo


class Metricsmetadata(BaseModel):
    """Metadata for a single metric"""


class MetricsmetadataResponse(APIResponse):
    """Response model for Metricsmetadata"""

    data: Metricsmetadata | None = None


class MetricsmetadataListResponse(APIResponse):
    """List response model for Metricsmetadata"""

    data: list[Metricsmetadata] = Field(default_factory=list)
    pagination: PaginationInfo | None = None
