# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Msteamsnotificationobject"""


from pydantic import BaseModel, Field

from .base import APIResponse, PaginationInfo


class Msteamsnotificationobject(BaseModel):
    """Properties of a Microsoft Teams notification service integration"""


class MsteamsnotificationobjectResponse(APIResponse):
    """Response model for Msteamsnotificationobject"""

    data: Msteamsnotificationobject | None = None


class MsteamsnotificationobjectListResponse(APIResponse):
    """List response model for Msteamsnotificationobject"""

    data: list[Msteamsnotificationobject] = Field(default_factory=list)
    pagination: PaginationInfo | None = None
