# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Msteamsnotification"""


from pydantic import BaseModel, Field

from .base import APIResponse, PaginationInfo


class Msteamsnotification(BaseModel):
    """Properties that link a notification to a Microsoft Teams integration"""


class MsteamsnotificationResponse(APIResponse):
    """Response model for Msteamsnotification"""

    data: Msteamsnotification | None = None


class MsteamsnotificationListResponse(APIResponse):
    """List response model for Msteamsnotification"""

    data: list[Msteamsnotification] = Field(default_factory=list)
    pagination: PaginationInfo | None = None
