# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Mtsqueryresponse"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Mtsqueryresponse(BaseModel):
    """MTS retrieval response body"""


class MtsqueryresponseResponse(APIResponse):
    """Response model for Mtsqueryresponse"""

    data: Optional[Mtsqueryresponse] = None


class MtsqueryresponseListResponse(APIResponse):
    """List response model for Mtsqueryresponse"""

    data: List[Mtsqueryresponse] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None
