# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Networkconnection"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Networkconnection(BaseModel):
    """Networkconnection model"""


class NetworkconnectionResponse(APIResponse):
    """Response model for Networkconnection"""

    data: Optional[Networkconnection] = None


class NetworkconnectionListResponse(APIResponse):
    """List response model for Networkconnection"""

    data: List[Networkconnection] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None
