# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Notfound"""


from pydantic import BaseModel, Field

from .base import APIResponse, PaginationInfo


class Notfound(BaseModel):
    """Not Found"""


class NotfoundResponse(APIResponse):
    """Response model for Notfound"""

    data: Notfound | None = None


class NotfoundListResponse(APIResponse):
    """List response model for Notfound"""

    data: list[Notfound] = Field(default_factory=list)
    pagination: PaginationInfo | None = None
