# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Opsgenienotification"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Opsgenienotification(BaseModel):
    """Properties that link a notification to a Opsgenie integration"""


class OpsgenienotificationResponse(APIResponse):
    """Response model for Opsgenienotification"""

    data: Optional[Opsgenienotification] = None


class OpsgenienotificationListResponse(APIResponse):
    """List response model for Opsgenienotification"""

    data: List[Opsgenienotification] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None
