# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Overmtslimit"""


from pydantic import BaseModel, Field

from .base import APIResponse, PaginationInfo


class Overmtslimit(BaseModel):
    """Indicates that a detector object matched too many MTS. Set by system."""


class OvermtslimitResponse(APIResponse):
    """Response model for Overmtslimit"""

    data: Overmtslimit | None = None


class OvermtslimitListResponse(APIResponse):
    """List response model for Overmtslimit"""

    data: list[Overmtslimit] = Field(default_factory=list)
    pagination: PaginationInfo | None = None
