# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Packagespecifications"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Packagespecifications(BaseModel):
    """For internal use only"""


class PackagespecificationsResponse(APIResponse):
    """Response model for Packagespecifications"""

    data: Optional[Packagespecifications] = None


class PackagespecificationsListResponse(APIResponse):
    """List response model for Packagespecifications"""

    data: List[Packagespecifications] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None
