# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Pagerdutynotification"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Pagerdutynotification(BaseModel):
    """Properties that link a notification to a PagerDuty integration"""


class PagerdutynotificationResponse(APIResponse):
    """Response model for Pagerdutynotification"""

    data: Optional[Pagerdutynotification] = None


class PagerdutynotificationListResponse(APIResponse):
    """List response model for Pagerdutynotification"""

    data: List[Pagerdutynotification] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None
