# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Paletteindex"""


from pydantic import BaseModel, Field

from .base import APIResponse, PaginationInfo


class Paletteindex(BaseModel):
    """Color to use for the publish object in a detector's table"""


class PaletteindexResponse(APIResponse):
    """Response model for Paletteindex"""

    data: Paletteindex | None = None


class PaletteindexListResponse(APIResponse):
    """List response model for Paletteindex"""

    data: list[Paletteindex] = Field(default_factory=list)
    pagination: PaginationInfo | None = None
