# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Parentdetectorid"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Parentdetectorid(BaseModel):
    """ID of the parent detector"""


class ParentdetectoridResponse(APIResponse):
    """Response model for Parentdetectorid"""

    data: Optional[Parentdetectorid] = None


class ParentdetectoridListResponse(APIResponse):
    """List response model for Parentdetectorid"""

    data: List[Parentdetectorid] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None
