# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Porttestresponse"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Porttestresponse(BaseModel):
    """Porttestresponse model"""


class PorttestresponseResponse(APIResponse):
    """Response model for Porttestresponse"""

    data: Optional[Porttestresponse] = None


class PorttestresponseListResponse(APIResponse):
    """List response model for Porttestresponse"""

    data: List[Porttestresponse] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None
