# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Publishlabeloption"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Publishlabeloption(BaseModel):
    """Display options for a plot in the detector's chart"""


class PublishlabeloptionResponse(APIResponse):
    """Response model for Publishlabeloption"""

    data: Optional[Publishlabeloption] = None


class PublishlabeloptionListResponse(APIResponse):
    """List response model for Publishlabeloption"""

    data: List[Publishlabeloption] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None
