# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Retrieveincidentresponse"""


from pydantic import BaseModel, Field

from .base import APIResponse, PaginationInfo


class Retrieveincidentresponse(BaseModel):
    """Properties of a single retrieved incident"""


class RetrieveincidentresponseResponse(APIResponse):
    """Response model for Retrieveincidentresponse"""

    data: Retrieveincidentresponse | None = None


class RetrieveincidentresponseListResponse(APIResponse):
    """List response model for Retrieveincidentresponse"""

    data: list[Retrieveincidentresponse] = Field(default_factory=list)
    pagination: PaginationInfo | None = None
