# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Retrieveincidentresponses"""


from pydantic import BaseModel, Field

from .base import APIResponse, PaginationInfo


class Retrieveincidentresponses(BaseModel):
    """List of incidents returned by a query retrieval"""


class RetrieveincidentresponsesResponse(APIResponse):
    """Response model for Retrieveincidentresponses"""

    data: Retrieveincidentresponses | None = None


class RetrieveincidentresponsesListResponse(APIResponse):
    """List response model for Retrieveincidentresponses"""

    data: list[Retrieveincidentresponses] = Field(default_factory=list)
    pagination: PaginationInfo | None = None
