# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Ruledetectlabel"""


from pydantic import BaseModel, Field

from .base import APIResponse, PaginationInfo


class Ruledetectlabel(BaseModel):
    """Label of the SignalFlow publish object for this rule"""


class RuledetectlabelResponse(APIResponse):
    """Response model for Ruledetectlabel"""

    data: Ruledetectlabel | None = None


class RuledetectlabelListResponse(APIResponse):
    """List response model for Ruledetectlabel"""

    data: list[Ruledetectlabel] = Field(default_factory=list)
    pagination: PaginationInfo | None = None
