# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Servicenownotification"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Servicenownotification(BaseModel):
    """Properties that link a notification to a Service Now integration"""


class ServicenownotificationResponse(APIResponse):
    """Response model for Servicenownotification"""

    data: Optional[Servicenownotification] = None


class ServicenownotificationListResponse(APIResponse):
    """List response model for Servicenownotification"""

    data: List[Servicenownotification] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None
