# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Slacknotification"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Slacknotification(BaseModel):
    """Properties that link a notification to a Slack integration"""


class SlacknotificationResponse(APIResponse):
    """Response model for Slacknotification"""

    data: Optional[Slacknotification] = None


class SlacknotificationListResponse(APIResponse):
    """List response model for Slacknotification"""

    data: List[Slacknotification] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None
