# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Slacknotification"""


from pydantic import BaseModel, Field

from .base import APIResponse, PaginationInfo


class Slacknotification(BaseModel):
    """Properties that link a notification to a Slack integration"""


class SlacknotificationResponse(APIResponse):
    """Response model for Slacknotification"""

    data: Slacknotification | None = None


class SlacknotificationListResponse(APIResponse):
    """List response model for Slacknotification"""

    data: list[Slacknotification] = Field(default_factory=list)
    pagination: PaginationInfo | None = None
