# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Status"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Status(BaseModel):
    """Analytics status of this detector"""


class StatusResponse(APIResponse):
    """Response model for Status"""

    data: Optional[Status] = None


class StatusListResponse(APIResponse):
    """List response model for Status"""

    data: List[Status] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None
