# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Stoptime"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Stoptime(BaseModel):
    """Ending timestamp of a muting rule, in *nix time in milliseconds"""


class StoptimeResponse(APIResponse):
    """Response model for Stoptime"""

    data: Optional[Stoptime] = None


class StoptimeListResponse(APIResponse):
    """List response model for Stoptime"""

    data: List[Stoptime] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None
