# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Tags"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Tags(BaseModel):
    """List of tags for the detector"""


class TagsResponse(APIResponse):
    """Response model for Tags"""

    data: Optional[Tags] = None


class TagsListResponse(APIResponse):
    """List response model for Tags"""

    data: List[Tags] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None
