# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Teamemailnotificationobject"""


from pydantic import BaseModel, Field

from .base import APIResponse, PaginationInfo


class Teamemailnotificationobject(BaseModel):
    """Properties of a team email notification"""


class TeamemailnotificationobjectResponse(APIResponse):
    """Response model for Teamemailnotificationobject"""

    data: Teamemailnotificationobject | None = None


class TeamemailnotificationobjectListResponse(APIResponse):
    """List response model for Teamemailnotificationobject"""

    data: list[Teamemailnotificationobject] = Field(default_factory=list)
    pagination: PaginationInfo | None = None
