# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Teamname"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Teamname(BaseModel):
    """Team name"""


class TeamnameResponse(APIResponse):
    """Response model for Teamname"""

    data: Optional[Teamname] = None


class TeamnameListResponse(APIResponse):
    """List response model for Teamname"""

    data: List[Teamname] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None
