# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Teamrequestbody"""


from pydantic import BaseModel, Field

from .base import APIResponse, PaginationInfo


class Teamrequestbody(BaseModel):
    """Request body"""


class TeamrequestbodyResponse(APIResponse):
    """Response model for Teamrequestbody"""

    data: Teamrequestbody | None = None


class TeamrequestbodyListResponse(APIResponse):
    """List response model for Teamrequestbody"""

    data: list[Teamrequestbody] = Field(default_factory=list)
    pagination: PaginationInfo | None = None
