# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Teamnotificationobject"""


from pydantic import BaseModel, Field

from .base import APIResponse, PaginationInfo


class Teamnotificationobject(BaseModel):
    """Properties of a team notification"""


class TeamnotificationobjectResponse(APIResponse):
    """Response model for Teamnotificationobject"""

    data: Teamnotificationobject | None = None


class TeamnotificationobjectListResponse(APIResponse):
    """List response model for Teamnotificationobject"""

    data: list[Teamnotificationobject] = Field(default_factory=list)
    pagination: PaginationInfo | None = None
