# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Testapiresponse"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Testapiresponse(BaseModel):
    """Testapiresponse model"""


class TestapiresponseResponse(APIResponse):
    """Response model for Testapiresponse"""

    data: Optional[Testapiresponse] = None


class TestapiresponseListResponse(APIResponse):
    """List response model for Testapiresponse"""

    data: List[Testapiresponse] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None
