# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Test"""


from pydantic import BaseModel, Field

from .base import APIResponse, PaginationInfo


class Test(BaseModel):
    """Properties of a test."""


class TestResponse(APIResponse):
    """Response model for Test"""

    data: Test | None = None


class TestListResponse(APIResponse):
    """List response model for Test"""

    data: list[Test] = Field(default_factory=list)
    pagination: PaginationInfo | None = None
