# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Time"""


from pydantic import BaseModel, Field

from .base import APIResponse, PaginationInfo


class Time(BaseModel):
    """Time range display options"""


class TimeResponse(APIResponse):
    """Response model for Time"""

    data: Time | None = None


class TimeListResponse(APIResponse):
    """List response model for Time"""

    data: list[Time] = Field(default_factory=list)
    pagination: PaginationInfo | None = None
