# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Tip"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Tip(BaseModel):
    """Plain text shown in an alert notification message"""


class TipResponse(APIResponse):
    """Response model for Tip"""

    data: Optional[Tip] = None


class TipListResponse(APIResponse):
    """List response model for Tip"""

    data: List[Tip] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None
