# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Updatedat"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Updatedat(BaseModel):
    """Timestamp of when the test was last updated, in UTC."""


class UpdatedatResponse(APIResponse):
    """Response model for Updatedat"""

    data: Optional[Updatedat] = None


class UpdatedatListResponse(APIResponse):
    """List response model for Updatedat"""

    data: List[Updatedat] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None
