# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Updatedetectorresponse"""


from pydantic import BaseModel, Field

from .base import APIResponse, PaginationInfo


class Updatedetectorresponse(BaseModel):
    """Response body returned by Update Detector"""


class UpdatedetectorresponseResponse(APIResponse):
    """Response model for Updatedetectorresponse"""

    data: Updatedetectorresponse | None = None


class UpdatedetectorresponseListResponse(APIResponse):
    """List response model for Updatedetectorresponse"""

    data: list[Updatedetectorresponse] = Field(default_factory=list)
    pagination: PaginationInfo | None = None
