# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Validatedetectorrequest"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Validatedetectorrequest(BaseModel):
    """Properties of the Validate Detector endpoint request body"""


class ValidatedetectorrequestResponse(APIResponse):
    """Response model for Validatedetectorrequest"""

    data: Optional[Validatedetectorrequest] = None


class ValidatedetectorrequestListResponse(APIResponse):
    """List response model for Validatedetectorrequest"""

    data: List[Validatedetectorrequest] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None
