# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Validateporttestresponse"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Validateporttestresponse(BaseModel):
    """Response body for validating a Port test."""


class ValidateporttestresponseResponse(APIResponse):
    """Response model for Validateporttestresponse"""

    data: Optional[Validateporttestresponse] = None


class ValidateporttestresponseListResponse(APIResponse):
    """List response model for Validateporttestresponse"""

    data: List[Validateporttestresponse] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None
