# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Validateapiresponse"""


from pydantic import BaseModel, Field

from .base import APIResponse, PaginationInfo


class Validateapiresponse(BaseModel):
    """Validateapiresponse model"""


class ValidateapiresponseResponse(APIResponse):
    """Response model for Validateapiresponse"""

    data: Validateapiresponse | None = None


class ValidateapiresponseListResponse(APIResponse):
    """List response model for Validateapiresponse"""

    data: list[Validateapiresponse] = Field(default_factory=list)
    pagination: PaginationInfo | None = None
