# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Valueprefix"""


from pydantic import BaseModel, Field

from .base import APIResponse, PaginationInfo


class Valueprefix(BaseModel):
    """Value to prepend to detector chart's data table values"""


class ValueprefixResponse(APIResponse):
    """Response model for Valueprefix"""

    data: Valueprefix | None = None


class ValueprefixListResponse(APIResponse):
    """List response model for Valueprefix"""

    data: list[Valueprefix] = Field(default_factory=list)
    pagination: PaginationInfo | None = None
