# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Variablevalue"""


from pydantic import BaseModel, Field

from .base import APIResponse, PaginationInfo


class Variablevalue(BaseModel):
    """The value of your variable."""


class VariablevalueResponse(APIResponse):
    """Response model for Variablevalue"""

    data: Variablevalue | None = None


class VariablevalueListResponse(APIResponse):
    """List response model for Variablevalue"""

    data: list[Variablevalue] = Field(default_factory=list)
    pagination: PaginationInfo | None = None
