# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Variablerequestbody"""


from pydantic import BaseModel, Field

from .base import APIResponse, PaginationInfo


class Variablerequestbody(BaseModel):
    """Request body"""


class VariablerequestbodyResponse(APIResponse):
    """Response model for Variablerequestbody"""

    data: Variablerequestbody | None = None


class VariablerequestbodyListResponse(APIResponse):
    """List response model for Variablerequestbody"""

    data: list[Variablerequestbody] = Field(default_factory=list)
    pagination: PaginationInfo | None = None
