# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Variable"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Variable(BaseModel):
    """Variable model"""


class VariableResponse(APIResponse):
    """Response model for Variable"""

    data: Optional[Variable] = None


class VariableListResponse(APIResponse):
    """List response model for Variable"""

    data: List[Variable] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None
