# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Variabledescription"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Variabledescription(BaseModel):
    """The description of your variable."""


class VariabledescriptionResponse(APIResponse):
    """Response model for Variabledescription"""

    data: Optional[Variabledescription] = None


class VariabledescriptionListResponse(APIResponse):
    """List response model for Variabledescription"""

    data: List[Variabledescription] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None
