# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Victoropsnotification"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Victoropsnotification(BaseModel):
    """Properties that link a notification to a Splunk On-Call integration object"""


class VictoropsnotificationResponse(APIResponse):
    """Response model for Victoropsnotification"""

    data: Optional[Victoropsnotification] = None


class VictoropsnotificationListResponse(APIResponse):
    """List response model for Victoropsnotification"""

    data: List[Victoropsnotification] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None
