# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /api/v1/applications/{name}/events operations"""

import logging
from typing import Dict, Any
from mcp_argocd.api.client import make_api_request, assemble_nested_body

# Configure logging
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger("mcp_tools")


async def application_service__list_resource_events(
    path_name: str,
    param_resourceNamespace: str = None,
    param_resourceName: str = None,
    param_resourceUID: str = None,
    param_appNamespace: str = None,
    param_project: str = None,
) -> Dict[str, Any]:
    '''
    ListResourceEvents returns a list of event resources.

    Args:
        path_name (str): The name of the application for which events are being listed.
        param_resourceNamespace (str, optional): The namespace of the resource. Defaults to None.
        param_resourceName (str, optional): The name of the resource. Defaults to None.
        param_resourceUID (str, optional): The unique identifier of the resource. Defaults to None.
        param_appNamespace (str, optional): The namespace of the application. Defaults to None.
        param_project (str, optional): The project associated with the application. Defaults to None.

    Returns:
        Dict[str, Any]: The JSON response from the API call containing the list of event resources.

    Raises:
        Exception: If the API request fails or returns an error.
    '''
    logger.debug("Making GET request to /api/v1/applications/{name}/events")

    params = {}
    data = {}

    if param_resourceNamespace is not None:
        params["resourceNamespace"] = (
            str(param_resourceNamespace).lower()
            if isinstance(param_resourceNamespace, bool)
            else param_resourceNamespace
        )

    if param_resourceName is not None:
        params["resourceName"] = (
            str(param_resourceName).lower() if isinstance(param_resourceName, bool) else param_resourceName
        )

    if param_resourceUID is not None:
        params["resourceUID"] = (
            str(param_resourceUID).lower() if isinstance(param_resourceUID, bool) else param_resourceUID
        )

    if param_appNamespace is not None:
        params["appNamespace"] = (
            str(param_appNamespace).lower() if isinstance(param_appNamespace, bool) else param_appNamespace
        )

    if param_project is not None:
        params["project"] = str(param_project).lower() if isinstance(param_project, bool) else param_project

    flat_body = {}
    data = assemble_nested_body(flat_body)

    success, response = await make_api_request(
        f"/api/v1/applications/{path_name}/events", method="GET", params=params, data=data
    )

    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get("error", "Request failed")}
    return response