# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /api/v1/applicationsets operations"""

import logging
from typing import Dict, Any, List
from mcp_argocd.api.client import make_api_request, assemble_nested_body

# Configure logging
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger("mcp_tools")


async def application_set_service__list(
    param_projects: List[str] = None, param_selector: str = None, param_appsetNamespace: str = None
) -> Dict[str, Any]:
    '''
    List returns a list of applicationsets.

    Args:
        param_projects (List[str], optional): The project names to restrict the returned list of applicationsets. Defaults to None.
        param_selector (str, optional): The selector to restrict the returned list to applications only with matched labels. Defaults to None.
        param_appsetNamespace (str, optional): The application set namespace. If not provided, defaults to the ArgoCD control plane namespace. Defaults to None.

    Returns:
        Dict[str, Any]: The JSON response from the API call containing the list of applicationsets.

    Raises:
        Exception: If the API request fails or returns an error.
    '''
    logger.debug("Making GET request to /api/v1/applicationsets")

    params = {}
    data = {}

    if param_projects is not None:
        params["projects"] = str(param_projects).lower() if isinstance(param_projects, bool) else param_projects

    if param_selector is not None:
        params["selector"] = str(param_selector).lower() if isinstance(param_selector, bool) else param_selector

    if param_appsetNamespace is not None:
        params["appsetNamespace"] = (
            str(param_appsetNamespace).lower() if isinstance(param_appsetNamespace, bool) else param_appsetNamespace
        )

    flat_body = {}
    data = assemble_nested_body(flat_body)

    success, response = await make_api_request("/api/v1/applicationsets", method="GET", params=params, data=data)

    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get("error", "Request failed")}
    return response


async def application_set_service__create(
    body_metadata_annotations: Dict[str, Any] = None,
    body_metadata_creationTimestamp: str = None,
    body_metadata_deletionGracePeriodSeconds: int = None,
    body_metadata_deletionTimestamp: str = None,
    body_metadata_finalizers: List[str] = None,
    body_metadata_generateName: str = None,
    body_metadata_generation: int = None,
    body_metadata_labels: Dict[str, Any] = None,
    body_metadata_managedFields: List[str] = None,
    body_metadata_name: str = None,
    body_metadata_namespace: str = None,
    body_metadata_ownerReferences: List[str] = None,
    body_metadata_resourceVersion: str = None,
    body_metadata_selfLink: str = None,
    body_metadata_uid: str = None,
    body_spec_applyNestedSelectors: bool = None,
    body_spec_generators: List[str] = None,
    body_spec_goTemplate: bool = None,
    body_spec_goTemplateOptions: List[str] = None,
    body_spec_ignoreApplicationDifferences: List[str] = None,
    body_spec_preservedFields_annotations: List[str] = None,
    body_spec_preservedFields_labels: List[str] = None,
    body_spec_strategy_rollingSync_steps: List[str] = None,
    body_spec_strategy_type: str = None,
    body_spec_syncPolicy_applicationsSync: str = None,
    body_spec_syncPolicy_preserveResourcesOnDeletion: bool = None,
    body_spec_template_metadata_annotations: Dict[str, Any] = None,
    body_spec_template_metadata_finalizers: List[str] = None,
    body_spec_template_metadata_labels: Dict[str, Any] = None,
    body_spec_template_metadata_name: str = None,
    body_spec_template_metadata_namespace: str = None,
    body_spec_template_spec_destination_name: str = None,
    body_spec_template_spec_destination_namespace: str = None,
    body_spec_template_spec_destination_server: str = None,
    body_spec_template_spec_ignoreDifferences: List[str] = None,
    body_spec_template_spec_info: List[str] = None,
    body_spec_template_spec_project: str = None,
    body_spec_template_spec_revisionHistoryLimit: int = None,
    body_spec_template_spec_source_chart: str = None,
    body_spec_template_spec_source_directory_exclude: str = None,
    body_spec_template_spec_source_directory_include: str = None,
    body_spec_template_spec_source_directory_jsonnet_extVars: List[str] = None,
    body_spec_template_spec_source_directory_jsonnet_libs: List[str] = None,
    body_spec_template_spec_source_directory_jsonnet_tlas: List[str] = None,
    body_spec_template_spec_source_directory_recurse: bool = None,
    body_spec_template_spec_source_helm_apiVersions: List[str] = None,
    body_spec_template_spec_source_helm_fileParameters: List[str] = None,
    body_spec_template_spec_source_helm_ignoreMissingValueFiles: bool = None,
    body_spec_template_spec_source_helm_kubeVersion: str = None,
    body_spec_template_spec_source_helm_namespace: str = None,
    body_spec_template_spec_source_helm_parameters: List[str] = None,
    body_spec_template_spec_source_helm_passCredentials: bool = None,
    body_spec_template_spec_source_helm_releaseName: str = None,
    body_spec_template_spec_source_helm_skipCrds: bool = None,
    body_spec_template_spec_source_helm_skipSchemaValidation: bool = None,
    body_spec_template_spec_source_helm_skipTests: bool = None,
    body_spec_template_spec_source_helm_valueFiles: List[str] = None,
    body_spec_template_spec_source_helm_values: str = None,
    body_spec_template_spec_source_helm_valuesObject_raw: str = None,
    body_spec_template_spec_source_helm_version: str = None,
    body_spec_template_spec_source_kustomize_apiVersions: List[str] = None,
    body_spec_template_spec_source_kustomize_commonAnnotations: Dict[str, Any] = None,
    body_spec_template_spec_source_kustomize_commonAnnotationsEnvsubst: bool = None,
    body_spec_template_spec_source_kustomize_commonLabels: Dict[str, Any] = None,
    body_spec_template_spec_source_kustomize_components: List[str] = None,
    body_spec_template_spec_source_kustomize_forceCommonAnnotations: bool = None,
    body_spec_template_spec_source_kustomize_forceCommonLabels: bool = None,
    body_spec_template_spec_source_kustomize_ignoreMissingComponents: bool = None,
    body_spec_template_spec_source_kustomize_images: List[str] = None,
    body_spec_template_spec_source_kustomize_kubeVersion: str = None,
    body_spec_template_spec_source_kustomize_labelIncludeTemplates: bool = None,
    body_spec_template_spec_source_kustomize_labelWithoutSelector: bool = None,
    body_spec_template_spec_source_kustomize_namePrefix: str = None,
    body_spec_template_spec_source_kustomize_nameSuffix: str = None,
    body_spec_template_spec_source_kustomize_namespace: str = None,
    body_spec_template_spec_source_kustomize_patches: List[str] = None,
    body_spec_template_spec_source_kustomize_replicas: List[str] = None,
    body_spec_template_spec_source_kustomize_version: str = None,
    body_spec_template_spec_source_name: str = None,
    body_spec_template_spec_source_path: str = None,
    body_spec_template_spec_source_plugin_env: List[str] = None,
    body_spec_template_spec_source_plugin_name: str = None,
    body_spec_template_spec_source_plugin_parameters: List[str] = None,
    body_spec_template_spec_source_ref: str = None,
    body_spec_template_spec_source_repoURL: str = None,
    body_spec_template_spec_source_targetRevision: str = None,
    body_spec_template_spec_sourceHydrator_drySource_path: str = None,
    body_spec_template_spec_sourceHydrator_drySource_repoURL: str = None,
    body_spec_template_spec_sourceHydrator_drySource_targetRevision: str = None,
    body_spec_template_spec_sourceHydrator_hydrateTo_targetBranch: str = None,
    body_spec_template_spec_sourceHydrator_syncSource_path: str = None,
    body_spec_template_spec_sourceHydrator_syncSource_targetBranch: str = None,
    body_spec_template_spec_sources: List[str] = None,
    body_spec_template_spec_syncPolicy_automated_allowEmpty: bool = None,
    body_spec_template_spec_syncPolicy_automated_enable: bool = None,
    body_spec_template_spec_syncPolicy_automated_prune: bool = None,
    body_spec_template_spec_syncPolicy_automated_selfHeal: bool = None,
    body_spec_template_spec_syncPolicy_managedNamespaceMetadata_annotations: Dict[str, Any] = None,
    body_spec_template_spec_syncPolicy_managedNamespaceMetadata_labels: Dict[str, Any] = None,
    body_spec_template_spec_syncPolicy_retry_backoff_duration: str = None,
    body_spec_template_spec_syncPolicy_retry_backoff_factor: int = None,
    body_spec_template_spec_syncPolicy_retry_backoff_maxDuration: str = None,
    body_spec_template_spec_syncPolicy_retry_limit: int = None,
    body_spec_template_spec_syncPolicy_syncOptions: List[str] = None,
    body_spec_templatePatch: str = None,
    body_status_applicationStatus: List[str] = None,
    body_status_conditions: List[str] = None,
    body_status_resources: List[str] = None,
    param_upsert: bool = False,
    param_dryRun: bool = False,
) -> Dict[str, Any]:
    '''
    Create an application set.

    Args:
        body_metadata_annotations (Dict[str, Any], optional): Annotations for the metadata. Defaults to None.
        body_metadata_creationTimestamp (str, optional): Creation timestamp for the metadata. Defaults to None.
        body_metadata_deletionGracePeriodSeconds (int, optional): Deletion grace period in seconds for the metadata. Defaults to None.
        body_metadata_deletionTimestamp (str, optional): Deletion timestamp for the metadata. Defaults to None.
        body_metadata_finalizers (List[str], optional): Finalizers for the metadata. Defaults to None.
        body_metadata_generateName (str, optional): Generate name for the metadata. Defaults to None.
        body_metadata_generation (int, optional): Generation number for the metadata. Defaults to None.
        body_metadata_labels (Dict[str, Any], optional): Labels for the metadata. Defaults to None.
        body_metadata_managedFields (List[str], optional): Managed fields for the metadata. Defaults to None.
        body_metadata_name (str, optional): Name for the metadata. Defaults to None.
        body_metadata_namespace (str, optional): Namespace for the metadata. Defaults to None.
        body_metadata_ownerReferences (List[str], optional): Owner references for the metadata. Defaults to None.
        body_metadata_resourceVersion (str, optional): Resource version for the metadata. Defaults to None.
        body_metadata_selfLink (str, optional): Self link for the metadata. Defaults to None.
        body_metadata_uid (str, optional): UID for the metadata. Defaults to None.
        body_spec_applyNestedSelectors (bool, optional): Apply nested selectors in the spec. Defaults to None.
        body_spec_generators (List[str], optional): Generators for the spec. Defaults to None.
        body_spec_goTemplate (bool, optional): Go template flag for the spec. Defaults to None.
        body_spec_goTemplateOptions (List[str], optional): Go template options for the spec. Defaults to None.
        body_spec_ignoreApplicationDifferences (List[str], optional): Ignore application differences in the spec. Defaults to None.
        body_spec_preservedFields_annotations (List[str], optional): Preserved fields annotations in the spec. Defaults to None.
        body_spec_preservedFields_labels (List[str], optional): Preserved fields labels in the spec. Defaults to None.
        body_spec_strategy_rollingSync_steps (List[str], optional): Rolling sync steps in the strategy spec. Defaults to None.
        body_spec_strategy_type (str, optional): Strategy type in the spec. Defaults to None.
        body_spec_syncPolicy_applicationsSync (str, optional): Applications sync policy in the spec. Defaults to None.
        body_spec_syncPolicy_preserveResourcesOnDeletion (bool, optional): Preserve resources on deletion in the sync policy spec. Defaults to None.
        body_spec_template_metadata_annotations (Dict[str, Any], optional): Annotations for the template metadata. Defaults to None.
        body_spec_template_metadata_finalizers (List[str], optional): Finalizers for the template metadata. Defaults to None.
        body_spec_template_metadata_labels (Dict[str, Any], optional): Labels for the template metadata. Defaults to None.
        body_spec_template_metadata_name (str, optional): Name for the template metadata. Defaults to None.
        body_spec_template_metadata_namespace (str, optional): Namespace for the template metadata. Defaults to None.
        body_spec_template_spec_destination_name (str, optional): Destination name in the template spec. Defaults to None.
        body_spec_template_spec_destination_namespace (str, optional): Destination namespace in the template spec. Defaults to None.
        body_spec_template_spec_destination_server (str, optional): Destination server in the template spec. Defaults to None.
        body_spec_template_spec_ignoreDifferences (List[str], optional): Ignore differences in the template spec. Defaults to None.
        body_spec_template_spec_info (List[str], optional): Info in the template spec. Defaults to None.
        body_spec_template_spec_project (str, optional): Project in the template spec. Defaults to None.
        body_spec_template_spec_revisionHistoryLimit (int, optional): Revision history limit in the template spec. Defaults to None.
        body_spec_template_spec_source_chart (str, optional): Source chart in the template spec. Defaults to None.
        body_spec_template_spec_source_directory_exclude (str, optional): Directory exclude in the source template spec. Defaults to None.
        body_spec_template_spec_source_directory_include (str, optional): Directory include in the source template spec. Defaults to None.
        body_spec_template_spec_source_directory_jsonnet_extVars (List[str], optional): Jsonnet external variables in the source directory template spec. Defaults to None.
        body_spec_template_spec_source_directory_jsonnet_libs (List[str], optional): Jsonnet libraries in the source directory template spec. Defaults to None.
        body_spec_template_spec_source_directory_jsonnet_tlas (List[str], optional): Jsonnet top-level arguments in the source directory template spec. Defaults to None.
        body_spec_template_spec_source_directory_recurse (bool, optional): Recurse flag in the source directory template spec. Defaults to None.
        body_spec_template_spec_source_helm_apiVersions (List[str], optional): Helm API versions in the source template spec. Defaults to None.
        body_spec_template_spec_source_helm_fileParameters (List[str], optional): Helm file parameters in the source template spec. Defaults to None.
        body_spec_template_spec_source_helm_ignoreMissingValueFiles (bool, optional): Ignore missing value files flag in the source helm template spec. Defaults to None.
        body_spec_template_spec_source_helm_kubeVersion (str, optional): Kubernetes version in the source helm template spec. Defaults to None.
        body_spec_template_spec_source_helm_namespace (str, optional): Namespace in the source helm template spec. Defaults to None.
        body_spec_template_spec_source_helm_parameters (List[str], optional): Helm parameters in the source template spec. Defaults to None.
        body_spec_template_spec_source_helm_passCredentials (bool, optional): Pass credentials flag in the source helm template spec. Defaults to None.
        body_spec_template_spec_source_helm_releaseName (str, optional): Release name in the source helm template spec. Defaults to None.
        body_spec_template_spec_source_helm_skipCrds (bool, optional): Skip CRDs flag in the source helm template spec. Defaults to None.
        body_spec_template_spec_source_helm_skipSchemaValidation (bool, optional): Skip schema validation flag in the source helm template spec. Defaults to None.
        body_spec_template_spec_source_helm_skipTests (bool, optional): Skip tests flag in the source helm template spec. Defaults to None.
        body_spec_template_spec_source_helm_valueFiles (List[str], optional): Helm value files in the source template spec. Defaults to None.
        body_spec_template_spec_source_helm_values (str, optional): Helm values in the source template spec. Defaults to None.
        body_spec_template_spec_source_helm_valuesObject_raw (str, optional): Raw values object in the source helm template spec. Defaults to None.
        body_spec_template_spec_source_helm_version (str, optional): Helm version in the source template spec. Defaults to None.
        body_spec_template_spec_source_kustomize_apiVersions (List[str], optional): Kustomize API versions in the source template spec. Defaults to None.
        body_spec_template_spec_source_kustomize_commonAnnotations (Dict[str, Any], optional): Common annotations in the source kustomize template spec. Defaults to None.
        body_spec_template_spec_source_kustomize_commonAnnotationsEnvsubst (bool, optional): Common annotations envsubst flag in the source kustomize template spec. Defaults to None.
        body_spec_template_spec_source_kustomize_commonLabels (Dict[str, Any], optional): Common labels in the source kustomize template spec. Defaults to None.
        body_spec_template_spec_source_kustomize_components (List[str], optional): Components in the source kustomize template spec. Defaults to None.
        body_spec_template_spec_source_kustomize_forceCommonAnnotations (bool, optional): Force common annotations flag in the source kustomize template spec. Defaults to None.
        body_spec_template_spec_source_kustomize_forceCommonLabels (bool, optional): Force common labels flag in the source kustomize template spec. Defaults to None.
        body_spec_template_spec_source_kustomize_ignoreMissingComponents (bool, optional): Ignore missing components flag in the source kustomize template spec. Defaults to None.
        body_spec_template_spec_source_kustomize_images (List[str], optional): Images in the source kustomize template spec. Defaults to None.
        body_spec_template_spec_source_kustomize_kubeVersion (str, optional): Kubernetes version in the source kustomize template spec. Defaults to None.
        body_spec_template_spec_source_kustomize_labelIncludeTemplates (bool, optional): Label include templates flag in the source kustomize template spec. Defaults to None.
        body_spec_template_spec_source_kustomize_labelWithoutSelector (bool, optional): Label without selector flag in the source kustomize template spec. Defaults to None.
        body_spec_template_spec_source_kustomize_namePrefix (str, optional): Name prefix in the source kustomize template spec. Defaults to None.
        body_spec_template_spec_source_kustomize_nameSuffix (str, optional): Name suffix in the source kustomize template spec. Defaults to None.
        body_spec_template_spec_source_kustomize_namespace (str, optional): Namespace in the source kustomize template spec. Defaults to None.
        body_spec_template_spec_source_kustomize_patches (List[str], optional): Patches in the source kustomize template spec. Defaults to None.
        body_spec_template_spec_source_kustomize_replicas (List[str], optional): Replicas in the source kustomize template spec. Defaults to None.
        body_spec_template_spec_source_kustomize_version (str, optional): Version in the source kustomize template spec. Defaults to None.
        body_spec_template_spec_source_name (str, optional): Source name in the template spec. Defaults to None.
        body_spec_template_spec_source_path (str, optional): Source path in the template spec. Defaults to None.
        body_spec_template_spec_source_plugin_env (List[str], optional): Plugin environment in the source template spec. Defaults to None.
        body_spec_template_spec_source_plugin_name (str, optional): Plugin name in the source template spec. Defaults to None.
        body_spec_template_spec_source_plugin_parameters (List[str], optional): Plugin parameters in the source template spec. Defaults to None.
        body_spec_template_spec_source_ref (str, optional): Source reference in the template spec. Defaults to None.
        body_spec_template_spec_source_repoURL (str, optional): Repository URL in the source template spec. Defaults to None.
        body_spec_template_spec_source_targetRevision (str, optional): Target revision in the source template spec. Defaults to None.
        body_spec_template_spec_sourceHydrator_drySource_path (str, optional): Dry source path in the source hydrator template spec. Defaults to None.
        body_spec_template_spec_sourceHydrator_drySource_repoURL (str, optional): Dry source repository URL in the source hydrator template spec. Defaults to None.
        body_spec_template_spec_sourceHydrator_drySource_targetRevision (str, optional): Dry source target revision in the source hydrator template spec. Defaults to None.
        body_spec_template_spec_sourceHydrator_hydrateTo_targetBranch (str, optional): Hydrate to target branch in the source hydrator template spec. Defaults to None.
        body_spec_template_spec_sourceHydrator_syncSource_path (str, optional): Sync source path in the source hydrator template spec. Defaults to None.
        body_spec_template_spec_sourceHydrator_syncSource_targetBranch (str, optional): Sync source target branch in the source hydrator template spec. Defaults to None.
        body_spec_template_spec_sources (List[str], optional): Sources in the template spec. Defaults to None.
        body_spec_template_spec_syncPolicy_automated_allowEmpty (bool, optional): Allow empty flag in the automated sync policy template spec. Defaults to None.
        body_spec_template_spec_syncPolicy_automated_enable (bool, optional): Enable flag in the automated sync policy template spec. Defaults to None.
        body_spec_template_spec_syncPolicy_automated_prune (bool, optional): Prune flag in the automated sync policy template spec. Defaults to None.
        body_spec_template_spec_syncPolicy_automated_selfHeal (bool, optional): Self-heal flag in the automated sync policy template spec. Defaults to None.
        body_spec_template_spec_syncPolicy_managedNamespaceMetadata_annotations (Dict[str, Any], optional): Annotations in the managed namespace metadata sync policy template spec. Defaults to None.
        body_spec_template_spec_syncPolicy_managedNamespaceMetadata_labels (Dict[str, Any], optional): Labels in the managed namespace metadata sync policy template spec. Defaults to None.
        body_spec_template_spec_syncPolicy_retry_backoff_duration (str, optional): Retry backoff duration in the sync policy template spec. Defaults to None.
        body_spec_template_spec_syncPolicy_retry_backoff_factor (int, optional): Retry backoff factor in the sync policy template spec. Defaults to None.
        body_spec_template_spec_syncPolicy_retry_backoff_maxDuration (str, optional): Retry backoff max duration in the sync policy template spec. Defaults to None.
        body_spec_template_spec_syncPolicy_retry_limit (int, optional): Retry limit in the sync policy template spec. Defaults to None.
        body_spec_template_spec_syncPolicy_syncOptions (List[str], optional): Sync options in the sync policy template spec. Defaults to None.
        body_spec_templatePatch (str, optional): Template patch. Defaults to None.
        body_status_applicationStatus (List[str], optional): Application status. Defaults to None.
        body_status_conditions (List[str], optional): Conditions in the status. Defaults to None.
        body_status_resources (List[str], optional): Resources in the status. Defaults to None.
        param_upsert (bool, optional): Upsert parameter. Defaults to False.
        param_dryRun (bool, optional): Dry run parameter. Defaults to False.

    Returns:
        Dict[str, Any]: The JSON response from the API call.

    Raises:
        Exception: If the API request fails or returns an error.
    '''
    logger.debug("Making POST request to /api/v1/applicationsets")

    params = {}
    data = {}

    if param_upsert is not None:
        params["upsert"] = str(param_upsert).lower() if isinstance(param_upsert, bool) else param_upsert

    if param_dryRun is not None:
        params["dryRun"] = str(param_dryRun).lower() if isinstance(param_dryRun, bool) else param_dryRun

    flat_body = {}
    if body_metadata_annotations is not None:
        flat_body["metadata_annotations"] = body_metadata_annotations
    if body_metadata_creationTimestamp is not None:
        flat_body["metadata_creationTimestamp"] = body_metadata_creationTimestamp
    if body_metadata_deletionGracePeriodSeconds is not None:
        flat_body["metadata_deletionGracePeriodSeconds"] = body_metadata_deletionGracePeriodSeconds
    if body_metadata_deletionTimestamp is not None:
        flat_body["metadata_deletionTimestamp"] = body_metadata_deletionTimestamp
    if body_metadata_finalizers is not None:
        flat_body["metadata_finalizers"] = body_metadata_finalizers
    if body_metadata_generateName is not None:
        flat_body["metadata_generateName"] = body_metadata_generateName
    if body_metadata_generation is not None:
        flat_body["metadata_generation"] = body_metadata_generation
    if body_metadata_labels is not None:
        flat_body["metadata_labels"] = body_metadata_labels
    if body_metadata_managedFields is not None:
        flat_body["metadata_managedFields"] = body_metadata_managedFields
    if body_metadata_name is not None:
        flat_body["metadata_name"] = body_metadata_name
    if body_metadata_namespace is not None:
        flat_body["metadata_namespace"] = body_metadata_namespace
    if body_metadata_ownerReferences is not None:
        flat_body["metadata_ownerReferences"] = body_metadata_ownerReferences
    if body_metadata_resourceVersion is not None:
        flat_body["metadata_resourceVersion"] = body_metadata_resourceVersion
    if body_metadata_selfLink is not None:
        flat_body["metadata_selfLink"] = body_metadata_selfLink
    if body_metadata_uid is not None:
        flat_body["metadata_uid"] = body_metadata_uid
    if body_spec_applyNestedSelectors is not None:
        flat_body["spec_applyNestedSelectors"] = body_spec_applyNestedSelectors
    if body_spec_generators is not None:
        flat_body["spec_generators"] = body_spec_generators
    if body_spec_goTemplate is not None:
        flat_body["spec_goTemplate"] = body_spec_goTemplate
    if body_spec_goTemplateOptions is not None:
        flat_body["spec_goTemplateOptions"] = body_spec_goTemplateOptions
    if body_spec_ignoreApplicationDifferences is not None:
        flat_body["spec_ignoreApplicationDifferences"] = body_spec_ignoreApplicationDifferences
    if body_spec_preservedFields_annotations is not None:
        flat_body["spec_preservedFields_annotations"] = body_spec_preservedFields_annotations
    if body_spec_preservedFields_labels is not None:
        flat_body["spec_preservedFields_labels"] = body_spec_preservedFields_labels
    if body_spec_strategy_rollingSync_steps is not None:
        flat_body["spec_strategy_rollingSync_steps"] = body_spec_strategy_rollingSync_steps
    if body_spec_strategy_type is not None:
        flat_body["spec_strategy_type"] = body_spec_strategy_type
    if body_spec_syncPolicy_applicationsSync is not None:
        flat_body["spec_syncPolicy_applicationsSync"] = body_spec_syncPolicy_applicationsSync
    if body_spec_syncPolicy_preserveResourcesOnDeletion is not None:
        flat_body["spec_syncPolicy_preserveResourcesOnDeletion"] = body_spec_syncPolicy_preserveResourcesOnDeletion
    if body_spec_template_metadata_annotations is not None:
        flat_body["spec_template_metadata_annotations"] = body_spec_template_metadata_annotations
    if body_spec_template_metadata_finalizers is not None:
        flat_body["spec_template_metadata_finalizers"] = body_spec_template_metadata_finalizers
    if body_spec_template_metadata_labels is not None:
        flat_body["spec_template_metadata_labels"] = body_spec_template_metadata_labels
    if body_spec_template_metadata_name is not None:
        flat_body["spec_template_metadata_name"] = body_spec_template_metadata_name
    if body_spec_template_metadata_namespace is not None:
        flat_body["spec_template_metadata_namespace"] = body_spec_template_metadata_namespace
    if body_spec_template_spec_destination_name is not None:
        flat_body["spec_template_spec_destination_name"] = body_spec_template_spec_destination_name
    if body_spec_template_spec_destination_namespace is not None:
        flat_body["spec_template_spec_destination_namespace"] = body_spec_template_spec_destination_namespace
    if body_spec_template_spec_destination_server is not None:
        flat_body["spec_template_spec_destination_server"] = body_spec_template_spec_destination_server
    if body_spec_template_spec_ignoreDifferences is not None:
        flat_body["spec_template_spec_ignoreDifferences"] = body_spec_template_spec_ignoreDifferences
    if body_spec_template_spec_info is not None:
        flat_body["spec_template_spec_info"] = body_spec_template_spec_info
    if body_spec_template_spec_project is not None:
        flat_body["spec_template_spec_project"] = body_spec_template_spec_project
    if body_spec_template_spec_revisionHistoryLimit is not None:
        flat_body["spec_template_spec_revisionHistoryLimit"] = body_spec_template_spec_revisionHistoryLimit
    if body_spec_template_spec_source_chart is not None:
        flat_body["spec_template_spec_source_chart"] = body_spec_template_spec_source_chart
    if body_spec_template_spec_source_directory_exclude is not None:
        flat_body["spec_template_spec_source_directory_exclude"] = body_spec_template_spec_source_directory_exclude
    if body_spec_template_spec_source_directory_include is not None:
        flat_body["spec_template_spec_source_directory_include"] = body_spec_template_spec_source_directory_include
    if body_spec_template_spec_source_directory_jsonnet_extVars is not None:
        flat_body["spec_template_spec_source_directory_jsonnet_extVars"] = (
            body_spec_template_spec_source_directory_jsonnet_extVars
        )
    if body_spec_template_spec_source_directory_jsonnet_libs is not None:
        flat_body["spec_template_spec_source_directory_jsonnet_libs"] = (
            body_spec_template_spec_source_directory_jsonnet_libs
        )
    if body_spec_template_spec_source_directory_jsonnet_tlas is not None:
        flat_body["spec_template_spec_source_directory_jsonnet_tlas"] = (
            body_spec_template_spec_source_directory_jsonnet_tlas
        )
    if body_spec_template_spec_source_directory_recurse is not None:
        flat_body["spec_template_spec_source_directory_recurse"] = body_spec_template_spec_source_directory_recurse
    if body_spec_template_spec_source_helm_apiVersions is not None:
        flat_body["spec_template_spec_source_helm_apiVersions"] = body_spec_template_spec_source_helm_apiVersions
    if body_spec_template_spec_source_helm_fileParameters is not None:
        flat_body["spec_template_spec_source_helm_fileParameters"] = body_spec_template_spec_source_helm_fileParameters
    if body_spec_template_spec_source_helm_ignoreMissingValueFiles is not None:
        flat_body["spec_template_spec_source_helm_ignoreMissingValueFiles"] = (
            body_spec_template_spec_source_helm_ignoreMissingValueFiles
        )
    if body_spec_template_spec_source_helm_kubeVersion is not None:
        flat_body["spec_template_spec_source_helm_kubeVersion"] = body_spec_template_spec_source_helm_kubeVersion
    if body_spec_template_spec_source_helm_namespace is not None:
        flat_body["spec_template_spec_source_helm_namespace"] = body_spec_template_spec_source_helm_namespace
    if body_spec_template_spec_source_helm_parameters is not None:
        flat_body["spec_template_spec_source_helm_parameters"] = body_spec_template_spec_source_helm_parameters
    if body_spec_template_spec_source_helm_passCredentials is not None:
        flat_body["spec_template_spec_source_helm_passCredentials"] = (
            body_spec_template_spec_source_helm_passCredentials
        )
    if body_spec_template_spec_source_helm_releaseName is not None:
        flat_body["spec_template_spec_source_helm_releaseName"] = body_spec_template_spec_source_helm_releaseName
    if body_spec_template_spec_source_helm_skipCrds is not None:
        flat_body["spec_template_spec_source_helm_skipCrds"] = body_spec_template_spec_source_helm_skipCrds
    if body_spec_template_spec_source_helm_skipSchemaValidation is not None:
        flat_body["spec_template_spec_source_helm_skipSchemaValidation"] = (
            body_spec_template_spec_source_helm_skipSchemaValidation
        )
    if body_spec_template_spec_source_helm_skipTests is not None:
        flat_body["spec_template_spec_source_helm_skipTests"] = body_spec_template_spec_source_helm_skipTests
    if body_spec_template_spec_source_helm_valueFiles is not None:
        flat_body["spec_template_spec_source_helm_valueFiles"] = body_spec_template_spec_source_helm_valueFiles
    if body_spec_template_spec_source_helm_values is not None:
        flat_body["spec_template_spec_source_helm_values"] = body_spec_template_spec_source_helm_values
    if body_spec_template_spec_source_helm_valuesObject_raw is not None:
        flat_body["spec_template_spec_source_helm_valuesObject_raw"] = (
            body_spec_template_spec_source_helm_valuesObject_raw
        )
    if body_spec_template_spec_source_helm_version is not None:
        flat_body["spec_template_spec_source_helm_version"] = body_spec_template_spec_source_helm_version
    if body_spec_template_spec_source_kustomize_apiVersions is not None:
        flat_body["spec_template_spec_source_kustomize_apiVersions"] = (
            body_spec_template_spec_source_kustomize_apiVersions
        )
    if body_spec_template_spec_source_kustomize_commonAnnotations is not None:
        flat_body["spec_template_spec_source_kustomize_commonAnnotations"] = (
            body_spec_template_spec_source_kustomize_commonAnnotations
        )
    if body_spec_template_spec_source_kustomize_commonAnnotationsEnvsubst is not None:
        flat_body["spec_template_spec_source_kustomize_commonAnnotationsEnvsubst"] = (
            body_spec_template_spec_source_kustomize_commonAnnotationsEnvsubst
        )
    if body_spec_template_spec_source_kustomize_commonLabels is not None:
        flat_body["spec_template_spec_source_kustomize_commonLabels"] = (
            body_spec_template_spec_source_kustomize_commonLabels
        )
    if body_spec_template_spec_source_kustomize_components is not None:
        flat_body["spec_template_spec_source_kustomize_components"] = (
            body_spec_template_spec_source_kustomize_components
        )
    if body_spec_template_spec_source_kustomize_forceCommonAnnotations is not None:
        flat_body["spec_template_spec_source_kustomize_forceCommonAnnotations"] = (
            body_spec_template_spec_source_kustomize_forceCommonAnnotations
        )
    if body_spec_template_spec_source_kustomize_forceCommonLabels is not None:
        flat_body["spec_template_spec_source_kustomize_forceCommonLabels"] = (
            body_spec_template_spec_source_kustomize_forceCommonLabels
        )
    if body_spec_template_spec_source_kustomize_ignoreMissingComponents is not None:
        flat_body["spec_template_spec_source_kustomize_ignoreMissingComponents"] = (
            body_spec_template_spec_source_kustomize_ignoreMissingComponents
        )
    if body_spec_template_spec_source_kustomize_images is not None:
        flat_body["spec_template_spec_source_kustomize_images"] = body_spec_template_spec_source_kustomize_images
    if body_spec_template_spec_source_kustomize_kubeVersion is not None:
        flat_body["spec_template_spec_source_kustomize_kubeVersion"] = (
            body_spec_template_spec_source_kustomize_kubeVersion
        )
    if body_spec_template_spec_source_kustomize_labelIncludeTemplates is not None:
        flat_body["spec_template_spec_source_kustomize_labelIncludeTemplates"] = (
            body_spec_template_spec_source_kustomize_labelIncludeTemplates
        )
    if body_spec_template_spec_source_kustomize_labelWithoutSelector is not None:
        flat_body["spec_template_spec_source_kustomize_labelWithoutSelector"] = (
            body_spec_template_spec_source_kustomize_labelWithoutSelector
        )
    if body_spec_template_spec_source_kustomize_namePrefix is not None:
        flat_body["spec_template_spec_source_kustomize_namePrefix"] = (
            body_spec_template_spec_source_kustomize_namePrefix
        )
    if body_spec_template_spec_source_kustomize_nameSuffix is not None:
        flat_body["spec_template_spec_source_kustomize_nameSuffix"] = (
            body_spec_template_spec_source_kustomize_nameSuffix
        )
    if body_spec_template_spec_source_kustomize_namespace is not None:
        flat_body["spec_template_spec_source_kustomize_namespace"] = body_spec_template_spec_source_kustomize_namespace
    if body_spec_template_spec_source_kustomize_patches is not None:
        flat_body["spec_template_spec_source_kustomize_patches"] = body_spec_template_spec_source_kustomize_patches
    if body_spec_template_spec_source_kustomize_replicas is not None:
        flat_body["spec_template_spec_source_kustomize_replicas"] = body_spec_template_spec_source_kustomize_replicas
    if body_spec_template_spec_source_kustomize_version is not None:
        flat_body["spec_template_spec_source_kustomize_version"] = body_spec_template_spec_source_kustomize_version
    if body_spec_template_spec_source_name is not None:
        flat_body["spec_template_spec_source_name"] = body_spec_template_spec_source_name
    if body_spec_template_spec_source_path is not None:
        flat_body["spec_template_spec_source_path"] = body_spec_template_spec_source_path
    if body_spec_template_spec_source_plugin_env is not None:
        flat_body["spec_template_spec_source_plugin_env"] = body_spec_template_spec_source_plugin_env
    if body_spec_template_spec_source_plugin_name is not None:
        flat_body["spec_template_spec_source_plugin_name"] = body_spec_template_spec_source_plugin_name
    if body_spec_template_spec_source_plugin_parameters is not None:
        flat_body["spec_template_spec_source_plugin_parameters"] = body_spec_template_spec_source_plugin_parameters
    if body_spec_template_spec_source_ref is not None:
        flat_body["spec_template_spec_source_ref"] = body_spec_template_spec_source_ref
    if body_spec_template_spec_source_repoURL is not None:
        flat_body["spec_template_spec_source_repoURL"] = body_spec_template_spec_source_repoURL
    if body_spec_template_spec_source_targetRevision is not None:
        flat_body["spec_template_spec_source_targetRevision"] = body_spec_template_spec_source_targetRevision
    if body_spec_template_spec_sourceHydrator_drySource_path is not None:
        flat_body["spec_template_spec_sourceHydrator_drySource_path"] = (
            body_spec_template_spec_sourceHydrator_drySource_path
        )
    if body_spec_template_spec_sourceHydrator_drySource_repoURL is not None:
        flat_body["spec_template_spec_sourceHydrator_drySource_repoURL"] = (
            body_spec_template_spec_sourceHydrator_drySource_repoURL
        )
    if body_spec_template_spec_sourceHydrator_drySource_targetRevision is not None:
        flat_body["spec_template_spec_sourceHydrator_drySource_targetRevision"] = (
            body_spec_template_spec_sourceHydrator_drySource_targetRevision
        )
    if body_spec_template_spec_sourceHydrator_hydrateTo_targetBranch is not None:
        flat_body["spec_template_spec_sourceHydrator_hydrateTo_targetBranch"] = (
            body_spec_template_spec_sourceHydrator_hydrateTo_targetBranch
        )
    if body_spec_template_spec_sourceHydrator_syncSource_path is not None:
        flat_body["spec_template_spec_sourceHydrator_syncSource_path"] = (
            body_spec_template_spec_sourceHydrator_syncSource_path
        )
    if body_spec_template_spec_sourceHydrator_syncSource_targetBranch is not None:
        flat_body["spec_template_spec_sourceHydrator_syncSource_targetBranch"] = (
            body_spec_template_spec_sourceHydrator_syncSource_targetBranch
        )
    if body_spec_template_spec_sources is not None:
        flat_body["spec_template_spec_sources"] = body_spec_template_spec_sources
    if body_spec_template_spec_syncPolicy_automated_allowEmpty is not None:
        flat_body["spec_template_spec_syncPolicy_automated_allowEmpty"] = (
            body_spec_template_spec_syncPolicy_automated_allowEmpty
        )
    if body_spec_template_spec_syncPolicy_automated_enable is not None:
        flat_body["spec_template_spec_syncPolicy_automated_enable"] = (
            body_spec_template_spec_syncPolicy_automated_enable
        )
    if body_spec_template_spec_syncPolicy_automated_prune is not None:
        flat_body["spec_template_spec_syncPolicy_automated_prune"] = body_spec_template_spec_syncPolicy_automated_prune
    if body_spec_template_spec_syncPolicy_automated_selfHeal is not None:
        flat_body["spec_template_spec_syncPolicy_automated_selfHeal"] = (
            body_spec_template_spec_syncPolicy_automated_selfHeal
        )
    if body_spec_template_spec_syncPolicy_managedNamespaceMetadata_annotations is not None:
        flat_body["spec_template_spec_syncPolicy_managedNamespaceMetadata_annotations"] = (
            body_spec_template_spec_syncPolicy_managedNamespaceMetadata_annotations
        )
    if body_spec_template_spec_syncPolicy_managedNamespaceMetadata_labels is not None:
        flat_body["spec_template_spec_syncPolicy_managedNamespaceMetadata_labels"] = (
            body_spec_template_spec_syncPolicy_managedNamespaceMetadata_labels
        )
    if body_spec_template_spec_syncPolicy_retry_backoff_duration is not None:
        flat_body["spec_template_spec_syncPolicy_retry_backoff_duration"] = (
            body_spec_template_spec_syncPolicy_retry_backoff_duration
        )
    if body_spec_template_spec_syncPolicy_retry_backoff_factor is not None:
        flat_body["spec_template_spec_syncPolicy_retry_backoff_factor"] = (
            body_spec_template_spec_syncPolicy_retry_backoff_factor
        )
    if body_spec_template_spec_syncPolicy_retry_backoff_maxDuration is not None:
        flat_body["spec_template_spec_syncPolicy_retry_backoff_maxDuration"] = (
            body_spec_template_spec_syncPolicy_retry_backoff_maxDuration
        )
    if body_spec_template_spec_syncPolicy_retry_limit is not None:
        flat_body["spec_template_spec_syncPolicy_retry_limit"] = body_spec_template_spec_syncPolicy_retry_limit
    if body_spec_template_spec_syncPolicy_syncOptions is not None:
        flat_body["spec_template_spec_syncPolicy_syncOptions"] = body_spec_template_spec_syncPolicy_syncOptions
    if body_spec_templatePatch is not None:
        flat_body["spec_templatePatch"] = body_spec_templatePatch
    if body_status_applicationStatus is not None:
        flat_body["status_applicationStatus"] = body_status_applicationStatus
    if body_status_conditions is not None:
        flat_body["status_conditions"] = body_status_conditions
    if body_status_resources is not None:
        flat_body["status_resources"] = body_status_resources
    data = assemble_nested_body(flat_body)

    success, response = await make_api_request("/api/v1/applicationsets", method="POST", params=params, data=data)

    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get("error", "Request failed")}
    return response