# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /api/v1/applications/manifestsWithFiles operations"""

import logging
from typing import Dict, Any
from mcp_argocd.api.client import make_api_request, assemble_nested_body

# Configure logging
logging.basicConfig(level=logging.DEBUG)
logger = logging.getLogger("mcp_tools")


async def application_service__get_manifests_with_files(
    body_chunk_chunk: str = None,
    body_query_appNamespace: str = None,
    body_query_checksum: str = None,
    body_query_name: str = None,
    body_query_project: str = None,
) -> Dict[str, Any]:
    '''
    GetManifestsWithFiles returns application manifests using provided files to generate them.

    Args:
        body_chunk_chunk (str, optional): The chunk of the body content used for generating manifests. Defaults to None.
        body_query_appNamespace (str, optional): The namespace of the application for querying manifests. Defaults to None.
        body_query_checksum (str, optional): The checksum value for verifying the integrity of the files used. Defaults to None.
        body_query_name (str, optional): The name of the application for which manifests are being requested. Defaults to None.
        body_query_project (str, optional): The project identifier associated with the application. Defaults to None.

    Returns:
        Dict[str, Any]: The JSON response from the API call containing the application manifests.

    Raises:
        Exception: If the API request fails or returns an error.
    '''
    logger.debug("Making POST request to /api/v1/applications/manifestsWithFiles")

    params = {}
    data = {}

    flat_body = {}
    if body_chunk_chunk is not None:
        flat_body["chunk_chunk"] = body_chunk_chunk
    if body_query_appNamespace is not None:
        flat_body["query_appNamespace"] = body_query_appNamespace
    if body_query_checksum is not None:
        flat_body["query_checksum"] = body_query_checksum
    if body_query_name is not None:
        flat_body["query_name"] = body_query_name
    if body_query_project is not None:
        flat_body["query_project"] = body_query_project
    data = assemble_nested_body(flat_body)

    success, response = await make_api_request(
        "/api/v1/applications/manifestsWithFiles", method="POST", params=params, data=data
    )

    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get("error", "Request failed")}
    return response