# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Tools for /tests/{id} operations"""

import logging
from typing import Any
from mcp_splunk.api.client import make_api_request, assemble_nested_body

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger("mcp_tools")


async def delete_test(path_id: str) -> Any:
    """
        Deletes a test specified in the {id} path parameter.

        OpenAPI Description:
            Deletes a Test.

    ## Requirements

    * You must have an organization access token with the API permission or a session token to use the API.
    * You need the Splunk Observability Cloud admin or power role.


        Args:

            path_id (str): ID of the test to delete.



        Returns:
            Any: The JSON response from the API call.

        Raises:
            Exception: If the API request fails or returns an error.
    """
    logger.debug("Making DELETE request to /tests/{id}")

    params = {}
    data = {}

    flat_body = {}
    data = assemble_nested_body(flat_body)

    success, response = await make_api_request(f"/tests/{path_id}", method="DELETE", params=params, data=data)

    if not success:
        logger.error(f"Request failed: {response.get('error')}")
        return {"error": response.get("error", "Request failed")}
    return response
