# Copyright 2025 CNOE
# SPDX-License-Identifier: Apache-2.0
# Generated by CNOE OpenAPI MCP Codegen tool

"""Model for Category"""

from typing import List, Optional
from pydantic import BaseModel, Field
from .base import APIResponse, PaginationInfo


class Category(BaseModel):
    """Category model"""


class CategoryResponse(APIResponse):
    """Response model for Category"""

    data: Optional[Category] = None


class CategoryListResponse(APIResponse):
    """List response model for Category"""

    data: List[Category] = Field(default_factory=list)
    pagination: Optional[PaginationInfo] = None
