import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  gettingStartedSidebar: [
    {
      type: 'doc',
      id: 'index', // docs/index.md
      label: 'Introduction',
    },
    {
      type: 'doc',
      id: 'getting-started/quick-start', // docs/getting-started/quick-start.md
      label: 'Quick Start',
    },
    {
      type: 'category',
      label: 'Setup',
      items: [
        {
          type: 'category',
          label: 'Docker',
          items: [
            {
              type: 'doc',
              id: 'getting-started/docker-compose/setup',
            },
            {
              type: 'doc',
              id: 'getting-started/docker-compose/configure-llms',
            },
            {
              type: 'doc',
              id: 'getting-started/docker-compose/configure-agent-secrets',
            },
          ],
        },
        {
          type: 'category',
          label: 'KinD',
          items: [
            {
              type: 'doc',
              id: 'getting-started/kind/setup',
            },
            {
              type: 'doc',
              id: 'getting-started/kind/configure-llms',
            },
            {
              type: 'doc',
              id: 'getting-started/kind/configure-agent-secrets',
            },
          ],
        },
        {
          type: 'category',
          label: 'EKS',
          items: [
            {
              type: 'doc',
              id: 'getting-started/eks/setup',
            },
            {
              type: 'doc',
              id: 'getting-started/eks/configure-llms',
            },
            {
              type: 'doc',
              id: 'getting-started/eks/configure-agent-secrets',
            },
          ],
        },
      ],
    },
    {
      type: 'doc',
      id: 'getting-started/local-development', // docs/getting-started/local-development.md
      label: 'Local Development',
    },
    {
      type: 'doc',
      id: 'getting-started/user-interfaces',    // docs/getting-started/user-interfaces.md
      label: 'User Interfaces',
    },
    {
      type: 'doc',
      id: 'getting-started/next-steps',         // docs/getting-started/next-steps.md
      label: 'Next Steps',
    },
  ],
  architectureSidebar: [{type: 'autogenerated', dirName: 'architecture'}],
  agentOpsSidebar: [{type: 'autogenerated', dirName: 'agent-ops'}],
  securitySidebar: [{type: 'autogenerated', dirName: 'security'}],
  usecasesSidebar: [{type: 'autogenerated', dirName: 'usecases'}],
  promptLibrarySidebar: [{type: 'autogenerated', dirName: 'prompt-library'}],
  agentsSidebar: [{type: 'autogenerated', dirName: 'agents'}],
  evaluationsSidebar: [{type: 'autogenerated', dirName: 'evaluations'}],
  contributingSidebar: [{type: 'autogenerated', dirName: 'contributing'}],
};

export default sidebars;
